
project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - Indonesia_analysis.qmd
    - Ethiopia_analysis.qmd
    - Nigeria_analysis.qmd
    - India_analysis.qmd

website:
  title: "MAP2 Five country study exploring digital adoption & resilience among MSEs"
  navbar:
    right:
      - href: Indonesia_analysis.qmd
        text: Indonesia
      - href: Ethiopia_analysis.qmd
        text: Ethiopia
      - href: Nigeria_analysis.qmd
        text: Nigeria
      - href: India_analysis.qmd
        text: India

format:
  html:
    keep-md: true
    toc: true
    toc-depth: 6
    toc-location: left



