
project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - cfi_map2_global.qmd
    - Brazil_analysis.qmd
    - Indonesia_analysis.qmd
    - Ethiopia_analysis.qmd
    - Nigeria_analysis.qmd
    - India_analysis.qmd
    - cfi_map2_insurance.qmd

website:
  title: "MAP2 Five country study exploring digital adoption & resilience among MSEs"
  navbar:
    right:
      - href: cfi_map2_global.qmd
        text: Global
      - href: Brazil_analysis.qmd
        text: Brazil
      - href: Indonesia_analysis.qmd
        text: Indonesia
      - href: Ethiopia_analysis.qmd
        text: Ethiopia
      - href: Nigeria_analysis.qmd
        text: Nigeria
      - href: India_analysis.qmd
        text: India
      - href: cfi_map2_insurance.qmd
        text: Insurance

format:
  html:
    keep-md: true
    toc: true
    toc-depth: 6
    toc-location: left

include-in-header: 
  - text: |
      <style>figure { padding: 3em 0 3em 0; }</style



