
---
title: "Global"
lightbox: true
---

```{r}
#| include: false

# Importing packaegs, functions declaring globals
source("R/packages.R")
source("R/utils.R")
source("R/globals.R")
source("R/functions.R")
source("R/viz_functions.R")
source("R/0_global_main_data.R")
source("R/specific_functions.R")

# Preparing and combining the enumeration data for all countries
enum_data_all <- bind_rows(
  map(COUNTRIES, compile_enumdata, weight_params = WEIGHT_PARAMS)
) %>% mutate(
  city = CITIES[country]
)

# Preparing and combining all of the main interview data for all countries
main_data_all <- bind_rows(
  map(COUNTRIES, compile_maindata, weight_params = WEIGHT_PARAMS)
) %>% mutate(
  city = CITIES[country]
)


```

## The business landscape 

```{r, fig.width = 12, fig.asp = 0.35}
#| label: fig-nbus_size_and_sector
#| echo: false
#| warning: false
#| fig-cap: "Businesses enumerated by size"

# Number of firms by size and sector

indicators <- c("business_total")
groups_l1 <- "country"
groups_l2 <- GROUPS[c("business_size_agg2")]

get_grid_area <- function(c) { 
     WEIGHT_PARAMS[[c]][["grid_area"]]
}

ests_total <- compute_summary_clusterlevel_2g(indicators, groups_l1, groups_l2, enum_data_all, keep = "total")

ests_density <- ests_total %>% 
  mutate(
      indicator_name = "Total businesses per km2", 
      grid_area = map_dbl(country, get_grid_area),
      total = total/grid_area, 
      total_low = total_low/grid_area, 
      total_upp = total_upp/grid_area
  )

ests <- bind_rows(ests_total, ests_density)

factor_params <- list(
  wrap_sizes = list(indicator_name = 40, indicator_group = 40, group_name = 40, group_cat_val = 60), 
  reverse_order = list(indicator_name = FALSE, indicator_group = FALSE, group_name = FALSE, group_cat_val = TRUE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params, include_valuelabel = TRUE, valuelabel_target = "total", valuelabel_type = "num") %>%
  mutate(
    city = CITIES[country]
  ) %>% 
  group_by(city, indicator_name) %>% 
  mutate(
      size_total = sum(total),
      share = total/size_total,
      valuelabel = paste0(pctclean(share, 0), "%"),
      #valuelabel = ifelse(total < 1e5, NA, valuelabel),
      barlabel = ifelse(group_cat_val == "More than 10 people", numclean(size_total), NA),
      barlabelpos = ifelse(group_cat_val == "More than 10 people", size_total, NA), 
    ) 

# Parameters to create figure

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "stack", labeltotal = TRUE, labeltotal_ndgy = FALSE, labeltotal_extendmax = FALSE, color = "white"), 
  valuelabels = list(show = TRUE, lab_vjust = 0.5, lab_hjust = 0.5, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "blue")
)

palette <- c("#41BBD9", "#FF9F1C")
names(palette) <- c("1-10 people", "More than 10 people")

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(nbreaks = 5, type = "number", expand = c(0,0), droplines = FALSE)
)

legend <- list(
  show = TRUE, 
  title = "Business size:", 
  nrows = 1, 
  ncols = 1, 
  reverse = TRUE
)

labels <- list(
  title = "Total estimated business population and population density in each study area",
  subtitle =  NULL,
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

vars <- list(
  xvar = "city", yvar = "total", fillvar = "group_cat_val"
)

facets <- list(
  type = "wrap", 
  rows = "indicator_group", 
  cols = "indicator_name", 
  scales = "free", 
  space = "free",
  drop_row_label = TRUE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)

fig_flex(fig_data, vars, facets = facets, figparams, scales, legend, labels, coord_flip = TRUE)

```


```{r, fig.width = 12, fig.asp = 0.35}
#| label: fig-nbus_sector
#| echo: false
#| warning: false
#| fig-cap: "Businesses enumerated by sector"

# Number of firms by size and sector

indicators <- c("business_total")
groups_l1 <- "city"
groups_l2 <- GROUPS[c("business_sector_agg3")]

ests <- compute_summary_clusterlevel_2g(indicators, groups_l1, groups_l2, enum_data_all %>% filter(business_size_agg2 == "1-10 people"  ), keep = "total") %>% 
  mutate(size = "1-10 people") %>% 
  bind_rows(
    compute_summary_clusterlevel_2g(indicators, groups_l1, groups_l2, enum_data_all %>% filter(business_size_agg2 == "More than 10 people"), keep = "total") %>%  mutate(size = "More than 10 people")
    )

factor_params <- list(
  wrap_sizes = list(indicator_name = 40, indicator_group = 40, group_name = 40, group_cat_val = 60), 
  reverse_order = list(indicator_name = FALSE, indicator_group = FALSE, group_name = FALSE, group_cat_val = TRUE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params, include_valuelabel = TRUE, valuelabel_target = "total", valuelabel_type = "num") %>% group_by(city, indicator_name, size) %>% 
  mutate(
      size_total = sum(total),
      share = total/size_total,
      valuelabel = paste0(pctclean(share, 0), "%"),
      #valuelabel = ifelse(total < 1e5, NA, valuelabel),
      barlabel = ifelse(group_cat_val == "Services: transportation, construction, repair, other", numclean(size_total), NA),
      barlabelpos = ifelse(group_cat_val == "Services: transportation, construction, repair, other", size_total, NA), 
    ) 

# Parameters to create figure

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "stack", labeltotal = TRUE, labeltotal_ndgy = TRUE, labeltotal_extendmax = TRUE, color = "white"), 
  valuelabels = list(show = TRUE, lab_vjust = 0.5, lab_hjust = 0.5, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "blue")
)

palette <- c("#41BBD9", "#CEE5F2", "#FF9F1C")
names(palette) <- c("Services: retail/wholesale trade (re-sale)", "Services: transportation, construction, repair, other", "Manufacturing")

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(limits = c(0, 1), nbreaks = 5, type = "percent", expand = c(0,0), droplines = FALSE)
)

legend <- list(
  show = TRUE, 
  title = "Business size:", 
  nrows = 1, 
  ncols = 1, 
  reverse = TRUE
)

labels <- list(
  title = "Share of businesses by industrial sector within size category",
  subtitle =  "Businesses (%)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

vars <- list(
  xvar = "city", yvar = "share", fillvar = "group_cat_val"
)

facets <- list(
  type = "wrap", 
  rows = "indicator_group", 
  cols = "size", 
  scales = "fixed", 
  space = "free",
  drop_row_label = TRUE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)

fig_flex(fig_data, vars, facets = facets, figparams, scales, legend, labels, coord_flip = TRUE)

```
```{r, fig.width = 12, fig.asp = 0.35}
#| label: fig-sample_chars
#| echo: false
#| warning: false
#| fig-cap: "Businesses enumerated by sector"

# Number of firms by size and sector

indicators <- c("business_size_agg2_shc_1", "business_size_agg2_shc_2_10",  "business_sector_agg3_shc_mfc" , "business_sector_agg3_shc_srv_resale", "business_sector_agg3_shc_srv_oth", "business_premise_shc_1", "business_premise_shc_2", "business_premise_shc_3", "resp_type_owner", "resp_type_manager", "resp_sex_men", "resp_sex_women")

groups <- GROUPS[c("city")]

ests <- compute_summary_mainlevel_1g(indicators, groups, main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 40, indicator_group = 40, group_name = 40, group_cat_val = 60), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = TRUE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params) %>% mutate(valuelabel = ifelse(mean < 0.05, NA, valuelabel))

# Parameters to create figure

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "stack", labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = TRUE, lab_vjust = 0.5, lab_hjust = 0.5, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE)
)

palette <- c("#A2C3A4", "#C4F1BE", "#FF9F1C", "#41BBD9", "#CEE5F2", "#BFD3C1", "#A2C3A4", "#C4F1BE", "#FF7B9C", "#CEE5F2", "#FF7B9C","#CEE5F2")
names(palette) <- unique(fig_data$indicator_name)

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(limits = c(0, 1), nbreaks = 2, type = "percent", expand = c(0,0), droplines = FALSE)
)

legend <- list(
  show = TRUE, 
  direction = "vertical", 
  title = NULL, 
  nrows = 2, 
  ncols = 6, 
  reverse = FALSE
)

labels <- list(
  title = "Composition of MSEs in sample",
  subtitle =  "MSEs (%)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

vars <- list(
  xvar = "group_cat_val", yvar = "mean", fillvar = "indicator_name"
)

facets <- list(
  type = "wrap", 
  wrap_nrows = 1,
  wrap_ncols = 5,
  rows = "indicator_group", 
  cols = "indicator_group", 
  scales = "fixed", 
  space = "free",
  drop_row_label = TRUE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)


fig_flex(fig_data, vars, facets = facets, figparams, scales, legend, labels, coord_flip = TRUE)

```

```{r, fig.width = 12, fig.asp = 0.35}
#| label: fig-mses_productivity
#| echo: false
#| warning: false
#| fig-cap: "MSE revenues and productivity"

# Firm performance: Monthly revenue and normalized sales per employee

indicators <- c("perf_rev_reports", "perf_rev_usd", "perf_revpdypemp_usd",  "perf_rev_ppp", "perf_revpdypemp_ppp")
groups <- GROUPS[c("city")]

ests <- compute_summary_mainlevel_1g(indicators, groups, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 60, indicator_group = 30, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = TRUE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params, include_valuelabel = FALSE) %>% 
  mutate(
    mean = ifelse(indicator == "perf_rev_reports", mean*100, mean), 
    mean_low = ifelse(indicator == "perf_rev_reports", mean_low*100, mean_low), 
    mean_upp = ifelse(indicator == "perf_rev_reports", mean_upp*100, mean_upp), 
    valuelabel = ifelse(indicator == "perf_rev_reports", paste0(pctclean(mean, 0), "%"), 
                        ifelse(str_detect(indicator, "perf_revphrpemp"), numclean(mean, 2), numclean(mean, 0))), 
    currency = ifelse(str_detect(indicator, "usd"), "Current USD", NA), 
    currency = ifelse(str_detect(indicator, "ppp"), "International $", currency), 
    currency = ifelse(is.na(currency), "Not applicable", currency), 
    indicator_name = str_trim(str_replace(indicator_name, "\\[USD\\]", "")), 
    indicator_name = str_trim(str_replace(indicator_name, "\\[International \\$\\]", ""))
    )

gdp_peremp <- wb_data(indicator = "SL.GDP.PCAP.EM.KD", country = COUNTRIES, return_wide = FALSE) %>% 
  select(country, year = date, gdp_pe_ppp = value) %>% 
  group_by(country) %>% 
  mutate(
    max_year = max(year), 
    gdp_pe_ppp_pd = gdp_pe_ppp/12/30.5
  ) %>% 
  filter(year == max_year) %>% 
  mutate(
    group_cat_val = CITIES[country], 
    indicator_name = "Daily sales per employee",
    mean = gdp_pe_ppp_pd, 
    currency = "International $"
    )
  
  
 labels <- list(
  title = "MSE revenues and productivity",
  subtitle = "Current USD (Average)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "dodge", position_width = 0.9, labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = TRUE, lab_hjust = 1, lab_ndgfcty = 70, lab_ndgdiry = -1, lab_ndgx = 0.5, lab_face = "plain", lab_size = 3.5), 
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

palette <- c("grey90", "#CEE5F2", "#41BBD9")
names(palette) <- unique(fig_data$currency)

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(limits = c(0, 1), nbreaks = 5, type = "number", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = TRUE
)

vars <- list(
  xvar = "group_cat_val", yvar = "mean", fillvar = "currency"
)

facets <- list(
  type = "wrap", 
  rows = "group_name", 
  nrows = 1, 
  ncols = 3,
  cols = "indicator_name", 
  scales = "free_x", 
  space = "free", 
  drop_row_label = FALSE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE) +
  geom_point(data = gdp_peremp, aes(x = group_cat_val, y = mean, color = "GDP per person employed (WDI)"), shape = 21, size = 2, stroke = 1.5, fill = "white") + 
  guides(color = guide_legend(title = NULL))

```
```{r, fig.width = 12, fig.asp = 0.45}
#| label: fig-mse_perf_subj
#| echo: false
#| warning: false
#| fig-cap: "Changes in MSE outcomes in past year"


indicators <- c("perf_sales_up", "perf_sales_same", "perf_sales_down", "perf_emp_up", "perf_emp_same",  "perf_emp_down", "perf_investment", "perf_newservices")       

groups <- GROUPS[c("city")]

ests <- compute_summary_mainlevel_1g(indicators, groups, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 40, indicator_group = 40, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)

labels <- list(
  title = "Changes in business outcomes in past year",
  subtitle =  "MSEs (%)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.9, color = "white", position = "dodge", fill = "#CEE5F2", position_width = 0.5, labeltotal = FALSE), 
  valuelabels = list(show = TRUE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

scales <- list(
  fillcolor = list(palette = NULL), 
  yaxis = list(limits = c(0, 1), nbreaks = 4, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "mean", fillvar = NULL
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "group_cat_val", 
  scales = "free_y", 
  space = "free", 
  drop_row_label = FALSE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)

```

## The small business owner 


```{r, fig.width = 12, fig.asp = 0.45}
#| label: fig-mse_owner_chars
#| echo: false
#| warning: false
#| fig-cap: "MSE owner characteristics"


indicators <- c("resp_education_agg4_shc_non", "resp_education_agg4_shc_pri", "resp_education_agg4_shc_sec", "resp_education_agg4_shc_trt", 
                 "resp_experience_agg5_shc_1", "resp_experience_agg5_shc_2_5", "resp_experience_agg5_shc_6_10", "resp_experience_agg5_shc_11_20", "resp_experience_agg5_shc_20", 
                "resp_age_agg6_shc_25", "resp_age_agg6_shc_2535", "resp_age_agg6_shc_3545", "resp_age_agg6_shc_4555", "resp_age_agg6_shc_5565", "resp_age_agg6_shc_65")

groups <- GROUPS[c("city")]

ests <- compute_summary_mainlevel_1g(indicators, groups, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 40, indicator_group = 40, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)

labels <- list(
  title = "Age, education and experience of small business owners or managers",
  subtitle =  "Owners or managers (%)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.9, color = "white", position = "dodge", fill = "#CEE5F2", position_width = 0.5, labeltotal = FALSE), 
  valuelabels = list(show = TRUE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

scales <- list(
  fillcolor = list(palette = NULL), 
  yaxis = list(limits = c(0, 1), nbreaks = 4, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "mean", fillvar = NULL
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "group_cat_val", 
  scales = "free_y", 
  space = "free", 
  drop_row_label = FALSE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)


```



```{r, fig.width = 12, fig.asp = 0.6}
#| label: fig-mse_owner_psych
#| echo: false
#| warning: false
#| fig-cap: "Pyschographic characrteristics of SME owners or managers, by gender"


indicators <- c("resp_motivation_entrep", "resp_motivation_lackopp", "resp_motivation_oth", 
                "resp_maingoal_grow",  "resp_maingoal_stab", "resp_maingoal_leave", 
                "resp_riskapproach_aggr", "resp_riskapproach_calc", "resp_riskapproach_avoid", 
                "resi_resp_attitude_chllng_1", "resi_resp_attitude_chllng_2", "resi_resp_attitude_chllng_3" , "resi_resp_attitude_chllng_4", "resp_psych_segment_shc_grow", "resp_psych_segment_shc_stab", "resp_psych_segment_shc_surv")

groups <- GROUPS[c("city")]

ests <- compute_summary_mainlevel_1g(indicators, groups, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 60, indicator_group = 30, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)

labels <- list(
   title = "Pyschographic characteristics of SME owners or managers",
  subtitle = "% of MSE owners or managers",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "dodge", position_width = 0.9, labeltotal = FALSE, fill = "#CEE5F2", color = "white"), 
  valuelabels = list(show = TRUE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

scales <- list(
  fillcolor = list(palette = NULL), 
  yaxis = list(limits = c(0, 1), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "mean", fillvar = NULL
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "group_cat_val", 
  scales = "free_y", 
  space = "free", 
  drop_row_label = FALSE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)


```

```{r, fig.width = 12, fig.asp = 0.4}
#| label: fig-reg_growth_gender
#| echo: false
#| warning: false
#| fig-cap: "Correlation between owner's motivations, goals and attitudes to risk"

# Defining regressions
  depvars <- c("resp_motivation_entrep", "resp_maingoal_grow", "resp_riskapproach_aggr", "resp_psych_segment_shc_grow")
  depvar_labels <- c("Identifies as an entrepreneur", "Main goal is to grow the business", "Approach to risk is aggressive ", "Growth and risk oriented")
  names(depvar_labels) <- depvars
  maineffects <- "resp_sex_women"
  effect_labels <- c("(Intercept)" = "Men", INDICATORS[maineffects])
  confounds <- c("resp_experience_c", "resp_education_agg4_shc_non", "resp_education_agg4_shc_sec", "resp_education_agg4_shc_trt")
  
combinations <- expand.grid(depvars, COUNTRIES, stringsAsFactors = FALSE)
depvars <- combinations[[1]]
countries <- combinations[[2]]
  
# Running regressions
ests <- bind_rows(
    #map(depvars, model_and_prepfig, maineffects, confounds = NULL, data = main_data_all, depvar_labels, effect_labels),
    map2(depvars, countries, model_and_prepfig, maineffect = maineffects, confounds = confounds, data = main_data_all, depvar_labels = depvar_labels, effect_labels = effect_labels)
  ) %>% mutate(effect_label = str_replace(effect_label, "Gender: ", ""))

factor_params <- list(
  wrap_sizes = list(depvar_label = 20, effect_label = 15, model_type = 25), 
  reverse_order = list(depvar_label = TRUE, effect_label = TRUE, model_type = FALSE), 
  order_vars = list(depvar_label = NULL, effect_label = NULL, model_type = NULL)
)

fig_data <- prep_reg_data_allcountries(prep_reg_factors(ests, factor_params, include_valuelabel = FALSE))

labels <- list(
      title = "Observational estimates of the relationship of owner's gender on the orientation of firms",
      subtitle = "The difference (in percentage points) between women and men owners on motivation, goals and approach to risk is shown with the red arrow",
      y = "Predicted probability (%)",
      x = NULL,
      caption = str_wrap("Notes: The results shown are based on a linear regression model that measures the effect of gender on several outcomes of interest. The 'unadjusted' model does not include any additional controls, while the 'adjusted' model includes controls for three variables: years of experience and educational attainment. The regression parameters are used to compute predicted probabilities for male and female business owners with the average years of experience running the business in the sample and with primary-level educational attainment.", 175)
    )

  barparams <- list(
  bars = list(width = 0.6, color = "grey90"), 
  valuelabels = list(show = FALSE, lab_vjust = 0, lab_hjust = 0, lab_ndgy = 0, lab_ndgx = 0.25, lab_face = "plain", lab_size = 3), 
  arrowlabels = list(show = TRUE, lab_vjust = 0.5, lab_hjust = 0.5, lab_ndgy = 0, lab_ndgx = -0.25,  lab_face = "plain", lab_size = 3)
) 

scales <- list(
  y = list(limits = c(0,1), position = "left"), 
  x = list(position = "bottom")
)

 facets <- list(type = "grid", cols ="depvar_label", rows = "country", scales = "free", space = "free", drop_row_label = FALSE) 
    
 fig_regests(fig_data, labels, facets = facets, barparams, scales, coord_flip = TRUE)


```

## Digital technology 

```{r, fig.width = 12, fig.asp = 0.55}
#| label: fig-digtech_overview
#| echo: false
#| warning: false
#| fig-cap: "Access to connectivity and devices"

indicators <- c("tech_has_device", "tech_has_internet", "tech_uses_website", names(main_data_all)[str_detect(names(main_data_all), "^(tech.+).(shc.+)$")], "tech_uses_ai", "tech_uses_digpayments", "tech_uses_digloans", "tech_uses_adoption_score")
indicators <- indicators[!str_detect(indicators, "NA")]
groups_l1 <- "city"
groups_l2 <- GROUPS[c("resp_sex_str")]

# Adjustment to data
main_data_all <- main_data_all %>% 
  mutate(
    tech_uses_messaging_shc_nam = ifelse(country == "Ethiopia" & is.na(tech_uses_messaging_shc_nam), 0, tech_uses_messaging_shc_nam), 
    tech_uses_socialmedia_shc_nam = ifelse(country == "Ethiopia" & is.na(tech_uses_socialmedia_shc_nam), 0, tech_uses_socialmedia_shc_nam), 
    tech_uses_software_shc_mol = ifelse(country == "Ethiopia" & is.na(tech_uses_software_shc_mol), 0, tech_uses_software_shc_mol), 
     tech_uses_software_shc_nam = ifelse(country %in% c("Ethiopia", "Nigeria") & is.na(tech_uses_software_shc_nam), 0, tech_uses_software_shc_nam), 
    )

ests <- compute_summary_mainlevel_2g(indicators, groups_l1, groups_l2, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 80, indicator_group = 50, group_name = 25, group_cat_val = 20), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)
fig_data <- tech_adoption_landscape(fig_data, wrap = factor_params[["wrap_sizes"]][["indicator_name"]])

labels <- list(
  title = "Adoption and frequency of use of digital technologies",
  subtitle =  "MSEs (%)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "tile", # One of "bar" or "tile"
  tiles = list(color = "white"), 
  valuelabels = list(show = TRUE, lab_hjust = 0.5, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE)
)

scales <- list(
  fillcolor = list(palette = "identity", direction = NULL), 
  yaxis = list(limits = c(0, 1), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = FALSE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "group_cat_val", fillvar = "fillcolor"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "city", 
  scales = "free", 
  space = "free",
  drop_row_label = FALSE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)

fig_flex(fig_data %>% filter(indicator_name != "Never used"), vars, facets, figparams, scales, legend, labels, coord_flip = TRUE) 

```

```{r, fig.width = 12, fig.asp = 0.4}
#| label: fig-reg_digtech_drivers
#| echo: false
#| warning: false
#| fig-cap: "Drivers of overall technology adoption"

# Defining regressions
  depvars <- c("tech_uses_adoption_score")
  depvar_labels <- INDICATORS[depvars]
  maineffects <- c("resp_sex_women", "resp_age_c_5yi", "resp_experience_c_5yi", "resp_education_agg2_shc_secormore", "resp_motivation_entrep", "resp_maingoal_grow", "resp_riskapproach_aggr")
  effect_labels <- c("(Intercept)" = "Baseline", INDICATORS[maineffects])

  
combinations <- expand.grid(depvars, COUNTRIES, stringsAsFactors = FALSE)
depvars <- combinations[[1]]
countries <- combinations[[2]]
  
# Running regressions
ests <- bind_rows(
    #map(depvars, model_and_prepfig, maineffects, confounds = NULL, data = main_data_all, depvar_labels, effect_labels),
    map2(depvars, countries, model_and_prepfig, maineffect = maineffects, confounds = NULL, data = main_data_all, depvar_labels = depvar_labels, effect_labels = effect_labels)
  )

# Preparing figure data
factor_params <- list(
  wrap_sizes = list(depvar_label = 20, effect_label = 55, model_type = 25), 
  reverse_order = list(depvar_label = TRUE, effect_label = TRUE, model_type = FALSE), 
  order_vars = list(depvar_label = NULL, effect_label = NULL, model_type = NULL)
)

fig_data <- prep_reg_data_allcountries(prep_reg_factors(ests, factor_params, include_valuelabel = FALSE))

 labels <- list(
      title = "Drivers of overall technology adoption",
      subtitle = "The effect of each predictor on technology adoption is shown with the red arrow",
      y = "Predicted technology adoption score [0-10]",
      x = NULL,
      caption = str_wrap("Notes: The results shown are based on a linear regression model that measures the effect of several owner and firm-level characteristics. The regression parameters are used to compute predicted probabilities for businesses with different degrees of technology adoption.", 175)
    )
 
 barparams <- list(
  bars = list(width = 0.6, color = "grey90"), 
  valuelabels = list(show = FALSE, lab_vjust = 0, lab_hjust = 0, lab_ndgy = 0, lab_ndgx = 0.25, lab_face = "plain", lab_size = 3), 
  arrowlabels = list(show = TRUE, lab_vjust = 0.5, lab_hjust = 0.5, lab_ndgy = 0, lab_ndgx = -0.25,  lab_face = "plain", lab_size = 3)
) 

scales <- list(
  y = list(position = "right"), 
  x = list(txtwrap = 50, position = "bottom")
)

facets <- list(type = "grid", cols ="country", rows = "depvar_label", scales = "free", space = "fixed", drop_row_label = TRUE) 
    
fig_regests(fig_data, labels, facets = facets, barparams, scales, coord_flip = TRUE)

```

```{r, fig.width = 12, fig.asp = 0.4}
#| label: fig-reg_digtech_resilience
#| echo: false
#| warning: false
#| fig-cap: "Relationship between overall technology adoption & resilience"

# Defining regressions
  depvars <- c("resi_capital_score_v2")
  depvar_labels <- INDICATORS[depvars]
  maineffects <- c("tech_uses_adoption_score")
  effect_labels <- c("(Intercept)" = "Baseline", INDICATORS[maineffects])
  confounds <- c("resp_experience_c", "resp_education_agg4_shc_non", "resp_education_agg4_shc_pri",  "resp_education_agg4_shc_trt")
  
combinations <- expand.grid(depvars, COUNTRIES, stringsAsFactors = FALSE)
depvars <- combinations[[1]]
countries <- combinations[[2]]
  
# Running regressions
ests <- bind_rows(
    map2(depvars, countries, model_and_prepfig, maineffect = maineffects, confounds = confounds, data = main_data_all, depvar_labels = depvar_labels, effect_labels = effect_labels),
    map2(depvars, countries, model_and_prepfig, maineffect = maineffects, confounds = NULL, data = main_data_all, depvar_labels = depvar_labels, effect_labels = effect_labels)
  )

# Preparing figure data
factor_params <- list(
  wrap_sizes = list(depvar_label = 20, effect_label = 55, model_type = 25), 
  reverse_order = list(depvar_label = TRUE, effect_label = TRUE, model_type = FALSE), 
  order_vars = list(depvar_label = NULL, effect_label = NULL, model_type = NULL)
)

fig_data <- prep_reg_data_allcountries(prep_reg_factors(ests, factor_params, include_valuelabel = FALSE))

 labels <- list(
      title = "Drivers of overall technology adoption",
      subtitle = "The effect of each predictor on technology adoption is shown with the red arrow",
      y = "Predicted resilience capital score [0-3]",
      x = NULL,
      caption = str_wrap("Notes: The results shown are based on a linear regression model that measures the effect of several owner and firm-level characteristics. The regression parameters are used to compute predicted probabilities for businesses with different degrees of technology adoption.", 175)
    )
 
 barparams <- list(
  bars = list(width = 0.6, color = "grey90"), 
  valuelabels = list(show = FALSE, lab_vjust = 0, lab_hjust = 0, lab_ndgy = 0, lab_ndgx = 0.25, lab_face = "plain", lab_size = 3), 
  arrowlabels = list(show = TRUE, lab_vjust = 0.5, lab_hjust = 0.5, lab_ndgy = 0, lab_ndgx = -0.25,  lab_face = "plain", lab_size = 3)
) 

scales <- list(
  y = list(position = "right"), 
  x = list(txtwrap = 50, position = "bottom")
)

facets <- list(type = "grid", cols ="country", rows = "model_type", scales = "free", space = "fixed", drop_row_label = FALSE) 
    
fig_regests(fig_data, labels, facets = facets, barparams, scales, coord_flip = TRUE)

```

```{r, fig.width = 12, fig.asp = 0.4}
#| label: fig-digtech_usecases
#| echo: false
#| warning: false
#| fig-cap: "Digital technology adoption by use case"

#indicators <- c("tech_cat_none", "tech_uses_messaging", "tech_uses_socialmedia", "tech_uses_website", "tech_uses_ecommerce", "tech_uses_software", "tech_uses_ai", "tech_uses_digpayments", "tech_uses_digloans")

indicators <- c("tech_function_comms", "tech_function_mkts", "tech_function_ops", "tech_function_epay", "tech_function_comms_30da", "tech_function_mkts_30da", "tech_function_ops_30da", 
                "tech_function_comms_7da", "tech_function_mkts_7da", "tech_function_ops_7da")

groups <- GROUPS[c("city")]

ests <- compute_summary_mainlevel_1g(indicators, groups, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 60, indicator_group = 40, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)

labels <- list(
  title = "Use-cases of digital technologies in use by MSEs",
  subtitle =  "MSEs (%)",
  yax_ti = NULL,
  xax_ti = NULL,
    caption = str_wrap("Notes: The functional use-case categories are defined as follows: 'Communicating with customers' includes use of messaging (e.g. Whatsapp) or social media apps (e.g. Facebook); 'Accessing markets' includes use of e-commerce platforms (e.g. Amazon) or a dedicated business website; 'Enterprise operations' includes use of digital applications or software (e.g. for booking, inventory management), including aritifical intelligence; 'Digital payment acceptance' includes use of any in-store POS device that accepts digital customer payments (credit or debit cards, mobile money, QR codes), or online payments. The frequency of use of digital payments acceptance is not available, and corresponds to whether the business has used any means of digitaly payment acceptance in hte past 12 months.", 175)
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "dodge", position_width = 0.9, labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = FALSE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

palette <- c("#A2C3A4", "#C4F1BE", "#FF9F1C")
names(palette) <- c("Uses", "30-day active", "7-day active")   

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(limits = c(0, 1), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_group", yvar = "mean", fillvar = "indicator_name"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "group_cat_val", 
  scales = "free", 
  space = "free", 
  drop_row_label = TRUE, 
  drop_col_label = FALSE, 
  add_dividers = TRUE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)


```

```{r, fig.width = 12, fig.asp = 0.4}
#| label: fig-digtech_use_depth
#| echo: false
#| warning: false
#| fig-cap: "Depth of digital technology adoption"

indicators <- c("tech_cat_none", "tech_cat_any1", "tech_cat_any2", "tech_cat_any3", "tech_cat_all4")
groups <- GROUPS[c("city")]

groups_l1 <- "city"
groups_l2 <- GROUPS[c("resp_sex_str")]

ests <- compute_summary_mainlevel_2g(indicators, groups_l1, groups_l2, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 60, indicator_group = 40, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)

labels <- list(
  title = "Depth of digital technologies used by MSEs",
  subtitle =  "MSEs (%)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = str_wrap("Notes: Four use-cases of digital technology are considered here: 'Communicating with customers', 'Accessing markets', 'Enterprise operations' and 'Merchant payments'. MSEs are classified with respect to whether they use digital technology for any one, any two, any three, all four or none of these use-cases.", 175)
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "dodge", position_width = 0.9, labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = FALSE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

palette <- c("#FF7B9C", "#CEE5F2")
names(palette) <- c("Women", "Men")   

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(limits = c(0, 0.6), nbreaks = 6, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "mean", fillvar = "group_cat_val"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "city", 
  scales = "free", 
  space = "free", 
  drop_row_label = TRUE, 
  drop_col_label = FALSE, 
  add_dividers = TRUE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)


```

```{r, fig.width = 12, fig.asp = 0.5}
#| label: fig-tech_adoptionfactors
#| echo: false
#| warning: false
#| fig-cap: "Digital technology adoption factors"

indicators <- c(names(main_data_all)[str_detect(names(main_data_all), "adopfactors")],
                names(main_data_all)[str_detect(names(main_data_all), "adopbenefits")], 
                names(main_data_all)[str_detect(names(main_data_all), "adopchllng")])

groups_l1 <- "city"
groups_l2 <- GROUPS[c("resp_sex_str")]

ests <- compute_summary_mainlevel_2g(indicators, groups_l1, groups_l2, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 60, indicator_group = 40, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)

labels <- list(
  title = "Digital technology adoption factors, benefits and challenges",
  subtitle =  "MSEs using digital solutions* (%)",
  yax_ti = NULL,
  xax_ti = NULL,
    caption = str_wrap("Notes: *These survey questions were only asked to businesses who reported using any of the following tehcnologies: messaging apps, social media, e-commerce platforms, software for business operations, a website or artificial intelligence.", 175)
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "dodge", position_width = 0.9, labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = FALSE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

palette <- c("#FF7B9C", "#CEE5F2")
names(palette) <- c("Women", "Men")   

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(limits = c(0, 1), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "mean", fillvar = "group_cat_val"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "city", 
  scales = "free", 
  space = "free", 
  drop_row_label = FALSE, 
  drop_col_label = FALSE, 
  add_dividers = TRUE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)

```

```{r, fig.width = 12, fig.asp = 0.4}
#| label: fig-reg_revprhr_digtechusecase
#| echo: false
#| warning: false
#| fig-cap: "Relationship between digital technology adoption and firm-level labor productivity"

# Defining regressions
  depvars <- c("perf_revpdypemp_usd")
  depvar_labels <- INDICATORS[depvars]
  maineffects <- c("tech_function_comms", "tech_function_mkts","tech_function_ops","tech_function_epay")
  effect_labels <- c("(Intercept)" = "No digital solutions used", INDICATORS[maineffects])
  confounds <- c("resp_experience_c", "resp_education_agg4_shc_non", "resp_education_agg4_shc_pri",  "resp_education_agg4_shc_trt")
  
combinations <- expand.grid(depvars, COUNTRIES, stringsAsFactors = FALSE)
depvars <- combinations[[1]]
countries <- combinations[[2]]
  
# Running regressions
ests <- bind_rows(
    #map(depvars, model_and_prepfig, maineffects, confounds = NULL, data = main_data_all, depvar_labels, effect_labels),
    map2(depvars, countries, model_and_prepfig, maineffect = maineffects, confounds = confounds, data = main_data_all, depvar_labels = depvar_labels, effect_labels = effect_labels)
  )

factor_params <- list(
  wrap_sizes = list(depvar_label = 25, effect_label = 70, model_type = 25), 
  reverse_order = list(depvar_label = TRUE, effect_label = TRUE, model_type = FALSE), 
  order_vars = list(depvar_label = NULL, effect_label = NULL, model_type = NULL)
)

fig_data <- prep_reg_data_allcountries(prep_reg_factors(ests, factor_params, include_valuelabel = FALSE)) %>%
 mutate(effect_label = str_replace(effect_label, ": Uses", ""))

 labels <- list(
      title = "Observational estimates of the effect of digital technology adoption on labor productivity",
      subtitle = "The effect of digital technology adoption on labor productivity is shown with the red arrow",
      y = NULL,
      x = NULL,
      caption = str_wrap("Notes: The results shown are based on a linear regression model that measures the effect of digital technology adoption on firm labor productivity. The 'unadjusted' model does not include any additional controls, while the 'adjusted' model includes controls for three variables: years of experience and educational attainment. The regression parameters are used to compute predicted probabilities for businesses with different types of technology adoption, with the average years of experience running the business in the sample and with secondary-level educational attainment.", 175)
    )

barparams <- list(
  bars = list(width = 0.6, color = "grey90"), 
  valuelabels = list(show = FALSE, lab_vjust = 0, lab_hjust = 0, lab_ndgy = 0, lab_ndgx = 0.25, lab_face = "plain", lab_size = 3), 
  arrowlabels = list(show = TRUE, lab_vjust = 0.5, lab_hjust = 0.5, lab_ndgy = 0, lab_ndgx = -0.25,  lab_face = "plain", lab_size = 3)
) 


miny <- round(min(fig_data$fig_data), 2) 
maxy <- round(max(fig_data$fig_data), 2) 
buffer <- (maxy - miny)/100
miny <- miny - buffer*2
if (miny > 0) { miny <- 0 }
maxy <- maxy + buffer*2

scales <- list(
  y = list(limits = c(miny,maxy), position = "left"), 
  x = list(position = "bottom")
)

 facets <- list(type = "grid", 
                rows ="depvar_label", 
                cols = "city", 
                scales = "free", 
                space = "free", 
                drop_row_label = TRUE) 
    
 fig_regests(fig_data, labels, facets = facets, barparams, scales, coord_flip = TRUE)


```


```{r, fig.width = 12, fig.asp = 0.4}
#| label: fig-reg_revprhr_digtechdepth
#| echo: false
#| warning: false
#| fig-cap: "Relationship between depth of digital technology adoption and firm-level labor productivity"


# Defining regressions
  depvars <- c("perf_revphrpemp_usd")
  depvar_labels <- INDICATORS[depvars]
  maineffects <- c("tech_cat_any1", "tech_cat_any2", "tech_cat_any3", "tech_cat_all4")
  effect_labels <- c("(Intercept)" = "No digital solutions used", INDICATORS[maineffects])
  confounds <- c("resp_experience_c", "resp_education_agg4_shc_non", "resp_education_agg4_shc_pri",  "resp_education_agg4_shc_trt", "resp_maingoal_grow", "resp_riskapproach_aggr")
  
combinations <- expand.grid(depvars, COUNTRIES, stringsAsFactors = FALSE)
depvars <- combinations[[1]]
countries <- combinations[[2]]
  
# Running regressions
ests <- bind_rows(
    #map(depvars, model_and_prepfig, maineffects, confounds = NULL, data = main_data_all, depvar_labels, effect_labels),
    map2(depvars, countries, model_and_prepfig, maineffect = maineffects, confounds = confounds, data = main_data_all, depvar_labels = depvar_labels, effect_labels = effect_labels)
  )

factor_params <- list(
  wrap_sizes = list(depvar_label = 60, effect_label = 70, model_type = 25), 
  reverse_order = list(depvar_label = TRUE, effect_label = TRUE, model_type = FALSE), 
  order_vars = list(depvar_label = NULL, effect_label = NULL, model_type = NULL)
)

fig_data <- prep_reg_data_allcountries(prep_reg_factors(ests, factor_params, include_valuelabel = FALSE)) %>% 
  mutate(effect_label = str_replace(effect_label, "Digital technology adoption: ", ""))


 labels <- list(
      title = "Observational estimates of the effect of depth of digital technology adoption on labor productivity",
      subtitle = "The effect of digital technology adoption on labor productivity is shows with the red arrow",
      y = NULL,
      x = NULL,
      caption = str_wrap("Notes: The results shown are based on a linear regression model that measures the effect of digital technology adoption
                      on firm labor productivity. The 'unadjusted' model does not include any additional controls,
                       while the 'adjusted' model includes controls for three variables: years of experience and educational attainment.
                       The regression parameters are used to compute predicted probabilities for businesses with different types of technology adoption,                    with the average years of experience running the business in the sample and with secondary-level educational attainment.", 175)
    )


 facets <- list(type = "grid", 
                rows ="depvar_label", 
                cols = "city", 
                scales = "free", 
                space = "free", 
                drop_row_label = TRUE) 

  miny <- round(min(fig_data$fig_data), 2) 
  maxy <- round(max(fig_data$fig_data), 2) 
  buffer <- (maxy - miny)/100
  miny <- miny - buffer*4
  if (miny > 0) { miny <- 0 }
  maxy <- maxy + buffer*4

scales <- list(
  y = list(limits = c(miny,maxy), position = "left"), 
  x = list(position = "bottom")
)

 fig_regests(fig_data, labels, facets = facets, barparams, scales, coord_flip = TRUE)
 
```

## Financial services 

```{r, fig.width = 12, fig.asp = 0.5}
#| label: fig-account_ownership
#| echo: false
#| warning: false
#| fig-cap: "Financical accounts and savings"


indicators <- c("fin_account_formal", "fin_owner_save", names(main_data_all)[str_detect(names(main_data_all), "bus_savings")])
groups_l1 <- "city"
groups_l2 <- GROUPS[c("resp_sex_str")]

ests <- compute_summary_mainlevel_2g(indicators, groups_l1, groups_l2, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 40, indicator_group = 25, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)

labels <- list(
  title = "Account ownership and business savings",
  subtitle =  "MSEs (%)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "dodge", position_width = 0.9, labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = FALSE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

palette <- c("#FF7B9C", "#CEE5F2")
names(palette) <- c("Women", "Men")     

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(limits = c(0, 1), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "mean", fillvar = "group_cat_val"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "city", 
  scales = "free_y", 
  space = "free", 
  drop_row_label = FALSE, 
  drop_col_label = FALSE, 
  add_dividers = TRUE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)


```

```{r, fig.width = 12, fig.asp = 0.35}
#| label: fig-payments
#| echo: false
#| warning: false
#| fig-cap: "Merchant payments"


indicators <- c(names(main_data_all)[str_detect(names(main_data_all), "merchpay")], "tech_function_epay")

groups_l1 <- "city"
groups_l2 <- GROUPS[c("resp_sex_str")]

ests <- compute_summary_mainlevel_2g(indicators, groups_l1, groups_l2, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 50, indicator_group = 25, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)

labels <- list(
  title = "Merchant payments: Methods used by business to accept customer payments (in past 12 months)",
  subtitle =  "MSEs (%)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "dodge", position_width = 0.9, labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = FALSE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

palette <- c("#FF7B9C", "#CEE5F2")
names(palette) <- c("Women", "Men")   

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(limits = c(0,1), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "mean", fillvar = "group_cat_val"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "city", 
  scales = "free_y", 
  space = "free", 
  drop_row_label = TRUE, 
  drop_col_label = FALSE, 
  add_dividers = TRUE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)

```
```{r, fig.width = 12, fig.asp = 0.5}
#| label: fig-credit_demand
#| echo: false
#| warning: false
#| fig-cap: "Demand for credit"

indicators <- names(main_data_all)[str_detect(names(main_data_all), "activeloan")]
indicators <- indicators[!str_detect(indicators, "da")]
indicators <- c("fin_demandloan", "fin_activeloan_da_any", indicators) 

groups_l1 <- "city"
groups_l2 <- GROUPS[c("resp_sex_str")]

ests <- compute_summary_mainlevel_2g(indicators, groups_l1, groups_l2, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 60, indicator_group = 25, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)

labels <- list(
  title = "Demand for credit and usage of loans (past 12 months)",
  subtitle =  "MSEs (%)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "dodge", position_width = 0.9, labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = FALSE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

palette <- c("grey70", "#A2C3A4", "#C4F1BE", "#FF7B9C", "#CEE5F2")
names(palette) <- c("All businesses", "1 person", "2-10 people", "Women", "Men")   

maxy <- round(max(fig_data$mean, na.rm = TRUE), 2)

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(limits = c(0, maxy), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "mean", fillvar = "group_cat_val"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "city", 
  scales = "free_y", 
  space = "free", 
  drop_row_label = FALSE, 
  drop_col_label = FALSE, 
  add_dividers = TRUE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)


```


```{r, fig.width = 12, fig.asp = 0.4}
#| label: fig-credit_denied
#| echo: false
#| warning: false
#| fig-cap: "Barriers to credit"


indicators <- c(names(main_data_all)[str_detect(names(main_data_all), "denied")])

groups_l1 <- "city"
groups_l2 <- GROUPS[c("resp_sex_str")]

ests <- compute_summary_mainlevel_2g(indicators, groups_l1, groups_l2, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 60, indicator_group = 25, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)

labels <- list(
  title = "Barriers to credit",
  subtitle =  "MSEs (%)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "dodge", position_width = 0.9, labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = FALSE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

palette <- c("grey70", "#A2C3A4", "#C4F1BE", "#FF7B9C", "#CEE5F2")
names(palette) <- c("All businesses", "1 person", "2-10 people", "Women", "Men")   

maxy <- round(max(fig_data$mean, na.rm = TRUE), 2)

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(limits = c(0, maxy), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "mean", fillvar = "group_cat_val"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "city", 
  scales = "free_y", 
  space = "free", 
  drop_row_label = FALSE, 
  drop_col_label = FALSE, 
  add_dividers = TRUE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)

```

```{r, fig.width = 12, fig.asp = 0.5}
#| label: fig-dfs_impacts
#| echo: false
#| warning: false
#| fig-cap: "Impacts of digital financial services"

indicators <- c("fin_dfs_user", names(main_data_all)[str_detect(names(main_data_all), "digital_benefits|digital_challenges")])

groups_l1 <- "city"
groups_l2 <- GROUPS[c("resp_sex_str")]

ests <- compute_summary_mainlevel_2g(indicators, groups_l1, groups_l2, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 60, indicator_group = 25, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)

labels <- list(
  title = "Demand for credit and usage of loans (past 12 months)",
  subtitle =  "MSEs (%)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "dodge", position_width = 0.9, labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = FALSE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

palette <- c("grey70", "#A2C3A4", "#C4F1BE", "#FF7B9C", "#CEE5F2")
names(palette) <- c("All businesses", "1 person", "2-10 people", "Women", "Men")   

maxy <- round(max(fig_data$mean, na.rm = TRUE), 2)

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(limits = c(0, maxy), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "mean", fillvar = "group_cat_val"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "city", 
  scales = "free_y", 
  space = "free", 
  drop_row_label = FALSE, 
  drop_col_label = FALSE, 
  add_dividers = TRUE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)


```

## Consumer protection

```{r, fig.width = 12, fig.asp = 0.4}
#| label: fig-cp_loanrepayment
#| echo: false
#| warning: false
#| fig-cap: "Challenges with loan repayment"

indicators <- c(names(main_data_all)[str_detect(names(main_data_all), "loanrepaydiff")])

groups_l1 <- "city"
groups_l2 <- GROUPS[c("fullsample")]

ests <- compute_summary_mainlevel_2g(indicators, groups_l1, groups_l2, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")  %>% 
  mutate(indicator_group = ifelse(str_detect(indicator, "cope"), "Coping strategy", indicator_group))

factor_params <- list(
  wrap_sizes = list(indicator_name = 60, indicator_group = 25, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)

labels <- list(
  title = "Demand for credit and usage of loans (past 12 months)",
  subtitle =  "MSEs (%)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "dodge", position_width = 0.9, labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = FALSE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

palette <- c("grey70", "#A2C3A4", "#C4F1BE", "#FF7B9C", "#CEE5F2")
names(palette) <- c("All businesses", "1 person", "2-10 people", "Women", "Men")   

maxy <- round(max(fig_data$mean, na.rm = TRUE), 2)

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(limits = c(0, maxy), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "mean", fillvar = "group_cat_val"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "city", 
  scales = "free_y", 
  space = "free", 
  drop_row_label = FALSE, 
  drop_col_label = FALSE, 
  add_dividers = TRUE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)


```

```{r, fig.width = 12, fig.asp = 0.55}
#| label: fig-cp_issues
#| echo: false
#| warning: false
#| fig-cap: "Consumer protection issues"

indicators <- c(names(main_data_all)[str_detect(names(main_data_all), "cp_issues|cp_complaint|cp_dfs_stopped")])

groups_l1 <- "city"
groups_l2 <- GROUPS[c("fullsample")]

ests <- compute_summary_mainlevel_2g(indicators, groups_l1, groups_l2, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 60, indicator_group = 25, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)

labels <- list(
  title = "Consumer protection issues",
  subtitle =  "MSEs (%)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "dodge", position_width = 0.9, labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = FALSE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

palette <- c("grey70", "#A2C3A4", "#C4F1BE", "#FF7B9C", "#CEE5F2")
names(palette) <- c("All businesses", "1 person", "2-10 people", "Women", "Men")   

maxy <- round(max(fig_data$mean, na.rm = TRUE), 2)

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(limits = c(0, maxy), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "mean", fillvar = "group_cat_val"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "city", 
  scales = "free_y", 
  space = "free", 
  drop_row_label = FALSE, 
  drop_col_label = FALSE, 
  add_dividers = TRUE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)

```

## Risks and Resilience

```{r, fig.width = 12, fig.asp = 0.35}
#| label: fig-risks_types
#| echo: false
#| warning: false
#| fig-cap: "Risks: General"


indicators <- c("risk_largestimpact_shc_corr", "risk_largestimpact_shc_cost", "risk_largestimpact_shc_crme", "risk_largestimpact_shc_frau", "risk_largestimpact_shc_hlth", "risk_largestimpact_shc_none", "risk_largestimpact_shc_othr", "risk_largestimpact_shc_wthr")

groups_l1 <- "city"
groups_l2 <- GROUPS[c("resp_sex_str")]

ests <- compute_summary_mainlevel_2g(indicators, groups_l1, groups_l2, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 40, indicator_group = 25, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests %>% filter(indicator_name != "No risks faced"), factor_params, valuelabel_thresh = 0.05)

labels <- list(
  title = "High impact shocks faced by MSEs",
  subtitle =  "In the last 36 months (3 years), which of the following risks had the largest impact (most costly) in terms of losses or expenses incurred by the business?",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "dodge", position_width = 0.9, labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = TRUE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

palette <- c("#FF7B9C", "#CEE5F2")
names(palette) <- c("Women", "Men")   

maxy <- round(max(fig_data$mean, na.rm = TRUE), 2)
buffer <- maxy/6

scales <- list(
  fillcolor = list(palette = palette), 
  yaxis = list(limits = c(0, maxy + buffer), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "mean", fillvar = "group_cat_val"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "city", 
  scales = "free_y", 
  space = "free",
  drop_row_label = TRUE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)


```

```{r, fig.width = 12, fig.asp = 0.35}
#| label: fig-risks_climate_types
#| echo: false
#| warning: false
#| fig-cap: "Risks: Climate"


indicators <- c("risk_weather_type_heat", "risk_weather_type_droughts", "risk_weather_type_floodstyphoon", "risk_weather_type_other", "risk_weather_type_any")

groups_l1 <- "city"
groups_l2 <- GROUPS[c("resp_sex_str")]

ests <- compute_summary_mainlevel_2g(indicators, groups_l1, groups_l2, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 40, indicator_group = 25, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params, valuelabel_thresh = 0.05)

labels <- list(
  title = "Climate shocks faced by MSEs",
  subtitle =  "In the last 36 months (3 years), has your business or the supply chain of your business experienced any of the following weather-related risks?",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = "Notes: *For Indonesia and India, extreme rain floods or landslides includes typhoons or cyclones"
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.8, position = "dodge", position_width = 0.9, labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = TRUE, lab_hjust = 0, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

palette <- c("#FF7B9C", "#CEE5F2")
names(palette) <- c("Women", "Men")     

scales <- list(
  fillcolor = list(palette = palette, direction = NULL), 
  yaxis = list(limits = c(0, 1), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "mean", fillvar = "group_cat_val"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "city", 
  scales = "free_y", 
  space = "free",
  drop_row_label = TRUE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)


```
```{r, fig.width = 12, fig.asp = 0.45}
#| label: fig-risks_impacts
#| echo: false
#| warning: false
#| fig-cap: "Risks: Impacts"


indicators <- c(names(main_data_all)[str_detect(names(main_data_all), "weather_impact")], names(main_data_all)[str_detect(names(main_data_all), "weather_cope")], names(main_data_all)[str_detect(names(main_data_all), "weather_cond")])

groups <- GROUPS[c("city")]

ests <- compute_summary_mainlevel_1g(indicators, groups, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 60, indicator_group = 25, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)

labels <- list(
  title = "Impacts and coping strategies of MSEs",
  subtitle =  "MSEs exposed to climate shock in past 36 months (%)",
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "tile", # One of "bar" or "tile"
  tiles = list(color = "white"), 
  valuelabels = list(show = TRUE, lab_hjust = 0.5, lab_face = "plain", lab_size = 3),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE, color = "#2374AB")
)

scales <- list(
  fillcolor = list(palette = "Blues", direction = 1), 
  yaxis = list(limits = c(0, 1), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = FALSE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "group_cat_val", fillvar = "mean"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "group_name", 
  scales = "free", 
  space = "free",
  drop_row_label = FALSE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)


```


```{r, fig.width = 12, fig.asp = 0.35}
#| label: fig-resilience_financial
#| echo: false
#| warning: false
#| fig-cap: "Financial resilience"

indicators <- c("resi_efunds_firm_diff_1",   "resi_efunds_firm_diff_2", "resi_efunds_firm_diff_3", "resi_efunds_firm_diff_4", 
  "resi_efunds_firm_source_family", "resi_efunds_firm_source_work", "resi_efunds_firm_source_firmcsh", "resi_efunds_firm_source_hhcsh", "resi_efunds_firm_source_borrow", "resi_efunds_firm_source_sellassets", "resi_efunds_firm_source_other")

groups <- GROUPS[("city")]

ests <- compute_summary_mainlevel_1g(indicators, groups, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 60, indicator_group = 40, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params, valuelabel_thresh = 0.05)


labels <- list(
  title = NULL, 
  subtitle =  NULL, 
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.9, position = "stack", labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = TRUE, lab_hjust = 0.5, lab_vjust = 0.5, lab_face = "plain", lab_size = 3),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE)
)

palette <- c("#A2C3A4", "#C4F1BE", "#FF9F1C", "#DB504A", "#31AFD4", "#CEE5F2", "#CE6A85", "#985277", "#FAA275", "#FF8C61", "grey80")
names(palette) <- unique(fig_data$indicator_name)

scales <- list(
  fillcolor = list(palette = palette, direction = NULL), 
  yaxis = list(limits = c(0, 1), nbreaks = 5, type = "percent", expand = NULL, droplines = FALSE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  direction = "horizontal",
  nrows = 2, 
  ncols = 1, 
  reverse = TRUE
)

vars <- list(
  xvar = "group_cat_val", yvar = "mean", fillvar = "indicator_name"
)

facets <- list(
  type = "grid", 
  rows = "group_name", 
  cols = "indicator_group", 
  scales = "free", 
  space = "free",
  drop_row_label = TRUE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)

p1 <- fig_flex(fig_data %>% filter(indicator %in% names(main_data_all)[str_detect(names(main_data_all), "efunds_firm_diff")]),
                     vars, facets, figparams, scales, legend, labels, coord_flip = TRUE) 

facets <- list(
  type = "grid", 
  rows = "group_name", 
  cols = "indicator_group", 
  scales = "free", 
  space = "free",
  drop_row_label = TRUE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)

p2 <- fig_flex(fig_data %>% filter(indicator %in% names(main_data_all)[str_detect(names(main_data_all), "efunds_firm_source")]),
                     vars, facets, figparams, scales, legend, labels, coord_flip = TRUE)  

p1 + p2 + plot_layout(axes = "collect") + 
  plot_annotation(title = "Financial resilience: Access to and source of emergency funds", subtitle = "MSEs (%)", 
                  theme = theme(plot.title = element_text(size = 12, hjust = 0, face = 'bold', color = 'black'))) 

```

```{r, fig.width = 12, fig.asp = 0.35}
#| label: fig-resilience_nonfinancial
#| echo: false
#| warning: false
#| fig-cap: "Non-financial dimensions of business resilience"

indicators <- c(names(main_data_all)[str_detect(names(main_data_all), "efunds_hh_owner")],
                names(main_data_all)[str_detect(names(main_data_all), "suppchain_cust")], 
                names(main_data_all)[str_detect(names(main_data_all), "network_conf")])
  
groups <- GROUPS[("city")]

ests <- compute_summary_mainlevel_1g(indicators, groups, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 60, indicator_group = 40, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)


labels <- list(
  title = NULL, 
  subtitle =  NULL, 
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "bar", # One of "bar" or "tile"
  bars = list(width = 0.9, position = "stack", labeltotal = FALSE, color = "white"), 
  valuelabels = list(show = FALSE, lab_hjust = 0.5, lab_vjust = 0.5, lab_face = "plain", lab_size = 3),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE)
)

palette <- c("#DB504A", "#31AFD4", "#A2C3A4", "#FF9F1C", "#DB504A", "#DB504A", "#FF9F1C", "#A2C3A4")
names(palette) <- unique(fig_data$indicator_name)

scales <- list(
  fillcolor = list(palette = palette, direction = NULL), 
  yaxis = list(limits = c(0, 1), nbreaks = 5, type = "percent", expand = NULL, droplines = FALSE)
)

legend <- list(
  show = TRUE, 
  title = NULL, 
  direction = "horizontal",
  nrows = 2, 
  ncols = 1, 
  reverse = TRUE
)

vars <- list(
  xvar = "group_cat_val", yvar = "mean", fillvar = "indicator_name"
)

facets <- list(
  type = "grid", 
  rows = "group_name", 
  cols = "indicator_group", 
  scales = "free", 
  space = "free",
  drop_row_label = TRUE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)


p1 <- fig_flex(fig_data %>% filter(indicator %in% names(main_data_all)[str_detect(names(main_data_all), "resi_efunds_hh_owner")]),
                     vars, facets, figparams, scales, legend, labels, coord_flip = TRUE) 


facets <- list(
  type = "grid", 
  rows = "group_name", 
  cols = "indicator_group", 
  scales = "free", 
  space = "free",
  drop_row_label = TRUE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)


p2 <- fig_flex(fig_data %>% filter(indicator %in% names(main_data_all)[str_detect(names(main_data_all), "suppchain_cust")]), 
               vars, facets, figparams, scales, legend, labels, coord_flip = TRUE) 

p3 <- fig_flex(fig_data %>% filter(indicator %in% names(main_data_all)[str_detect(names(main_data_all), "network_conf")]), 
                     vars, facets, figparams, scales, legend, labels, coord_flip = TRUE) 


p1 + p2 + p3 + plot_layout(axes = "collect") + 
  plot_annotation(title = "Non-financial dimensions of business resilience", 
                  subtitle = "MSEs (%)", 
                  theme = theme(plot.title = element_text(size = 12, hjust = 0, face = 'bold', color = 'black'))) 


```


```{r, fig.width = 12, fig.asp = 0.35}
#| label: fig-resilience_overview
#| echo: false
#| warning: false
#| fig-cap: "Access to connectivity and devices"

indicators <- c(names(main_data_all)[str_detect(names(main_data_all), "resi_capital")])
groups_l1 <- "city"
groups_l2 <- GROUPS[c("resp_sex_str")]

ests <- compute_summary_mainlevel_2g(indicators, groups_l1, groups_l2, data = main_data_all, weights = "weight_msme", psu = NULL, keep = "mean")

factor_params <- list(
  wrap_sizes = list(indicator_name = 80, indicator_group = 25, group_name = 25, group_cat_val = NULL), 
  reverse_order = list(indicator_name = TRUE, indicator_group = FALSE, group_name = FALSE, group_cat_val = FALSE), 
  order_vars = list(indicator_name = NULL, indicator_group = NULL, group_name = NULL, group_cat_val = NULL)
)

fig_data <- prep_fig_data(ests, factor_params)
fig_data <- resilience_capital(fig_data)

labels <- list(
  title = "Resilience capital",
  subtitle =  NULL,
  yax_ti = NULL,
  xax_ti = NULL,
  caption = NULL
)

figparams <- list(
  geom_type = "tile", # One of "bar" or "tile"
  tiles = list(color = "white"), 
  valuelabels = list(show = TRUE, lab_hjust = 0.5, lab_face = "plain", lab_size = 3.5),
  catlabels = list(show = FALSE), 
  errorbars = list(show = FALSE)
)

scales <- list(
  fillcolor = list(palette = "identity", direction = NULL), 
  yaxis = list(limits = c(0, 1), nbreaks = 5, type = "percent", expand = NULL, droplines = TRUE)
)

legend <- list(
  show = FALSE, 
  title = NULL, 
  nrows = 1, 
  ncols = 1, 
  reverse = FALSE
)

vars <- list(
  xvar = "indicator_name", yvar = "group_cat_val", fillvar = "fillcolor"
)

facets <- list(
  type = "grid", 
  rows = "indicator_group", 
  cols = "city", 
  scales = "free", 
  space = "free",
  drop_row_label = TRUE, 
  drop_col_label = FALSE, 
  add_dividers = FALSE
)

fig_flex(fig_data, vars, facets, figparams, scales, legend, labels, coord_flip = TRUE) + geom_vline(xintercept = c(1.5, 2.5), color = "black")


```


```{r, fig.width = 12, fig.asp = 0.4}
#| label: fig-reg_resilience_digtechadoption
#| echo: false
#| warning: false
#| fig-cap: "Relationship between prior exposure to weather shock and investment in adaptation"


# Defining regressions
  depvars <- c("risk_weather_adaptspend")
  depvar_labels <- INDICATORS[depvars]
  maineffects <- c("risk_weather_type_any")
  effect_labels <- c("(Intercept)" = "No exposure to prior weather shock", INDICATORS[maineffects])
  confounds <- c("resp_experience_c", "resp_education_agg4_shc_non", "resp_education_agg4_shc_pri",  "resp_education_agg4_shc_trt", "resp_maingoal_grow", "resp_riskapproach_aggr")
  
combinations <- expand.grid(depvars, COUNTRIES, stringsAsFactors = FALSE)
depvars <- combinations[[1]]
countries <- combinations[[2]]
  
# Running regressions
ests <- bind_rows(
    map2(depvars, countries, model_and_prepfig, maineffect = maineffects, confounds = NULL, data = main_data_all, depvar_labels = depvar_labels, effect_labels = effect_labels),
    map2(depvars, countries, model_and_prepfig, maineffect = maineffects, confounds = confounds, data = main_data_all, depvar_labels = depvar_labels, effect_labels = effect_labels)
  )

factor_params <- list(
  wrap_sizes = list(depvar_label = 25, effect_label = 70, model_type = 25), 
  reverse_order = list(depvar_label = TRUE, effect_label = TRUE, model_type = FALSE), 
  order_vars = list(depvar_label = NULL, effect_label = NULL, model_type = NULL)
)

fig_data <- prep_reg_data_allcountries(prep_reg_factors(ests, factor_params, include_valuelabel = FALSE)) %>% 
  mutate(effect_label = str_replace(effect_label, "Climate risk: ", ""))


 labels <- list(
      title = "Observational estimates of the effect of exposure to weather shocks on investments in adaptation",
      subtitle = "The effect of prior exposure to a weather shock on investment in adaptations is shown with the red arrow",
      y = NULL,
      x = NULL,
      caption = str_wrap("Notes: The results shown are based on a linear regression model that measures the effect of digital technology adoption
                      on firm labor productivity. The 'unadjusted' model does not include any additional controls,
                       while the 'adjusted' model includes controls for three variables: years of experience and educational attainment.
                       The regression parameters are used to compute predicted probabilities for businesses with different types of technology adoption,                    with the average years of experience running the business in the sample and with secondary-level educational attainment.", 175)
    )


 facets <- list(type = "grid", 
                rows ="model_type", 
                cols = "city", 
                scales = "free", 
                space = "free", 
                drop_row_label = FALSE) 

  miny <- round(min(fig_data$fig_data), 2) 
  maxy <- round(max(fig_data$fig_data), 2) 
  buffer <- (maxy - miny)/100
  miny <- miny - buffer*4
  if (miny > 0) { miny <- 0 }
  maxy <- maxy + buffer*4

scales <- list(
  y = list(limits = c(miny,maxy), position = "left"), 
  x = list(position = "bottom")
)

 fig_regests(fig_data, labels, facets = facets, barparams, scales, coord_flip = TRUE)
 
```
