########################################################################

# Global parameters  --------------------------

#####################################################################################

COUNTRIES <- c("Indonesia", "Brazil", "Ethiopia", "Nigeria", "India")
CITIES <- c("Jakarta", "Sao Paulo", "Addis Ababa", "Lagos", "Delhi")
names(CITIES) <- COUNTRIES

WEIGHT_PARAMS <- list(
  "Indonesia" = list("N" = 26293, "n" = 96, "restricted_blocks" = c(23582, 26105, 21436, 16723), "grid_area" = 593),
  "Brazil" = list("N" = NULL, "n" = NULL,  "restricted_blocks" = NULL, "grid_area" = 1015),
  "Ethiopia" = list("N" = 15842, "n" = 98, "restricted_blocks" = c(3585,10239), "grid_area" = 361),
  "Nigeria" = list("N" = 9282, "n" = 99,  "restricted_blocks" = c(2851), "grid_area" = 208),
  "India" = list("N" = 30880, "n" = 98,  "restricted_blocks" = NULL, "grid_area" = 893)
  )

# Exchange rates per USD at 01 June 2024 (LCU per USD) from UN Treasures
# https://treasury.un.org/operationalrates/OperationalRates.php

FX_RATES <- list(
  "Indonesia" = 16262,
  "Brazil" = 5.203,
  "Ethiopia" = 57.042,
  "Nigeria" = 1435.3,
  "India" = 83.31
)

INDICATORS <- c("N_business_total_percluster" = "Population estimate: Total businesses (N)",
                "business_total" = "Population estimate: Total businesses (N)",
                "resp_sex_men" = "Gender: Men",
                "resp_sex_women" = "Gender: Women",
                "resp_education_agg2_shc_priorless" = "Educational attainment: Primary or less",
                "resp_education_agg2_shc_secormore" = "Educational attainment: Secondary or higher",
                "resp_education_agg4_shc_non" = "Educational attainment: Some primary or none",
                "resp_education_agg4_shc_pri" = "Educational attainment: Completed primary or some secondary",
                "resp_education_agg4_shc_sec" = "Educational attainment: Completed secondary or some university/technical school",
                "resp_education_agg4_shc_trt" = "Educational attainment: Completed university/technical school",
                "resp_experience_c" = "Experience running business: Continuous (single years)", 
                "resp_experience_agg5_shc_1" = "Experience running business: 1 yr or less",
                "resp_experience_agg5_shc_2_5" = "Experience running business: 2-5 yrs",
                "resp_experience_agg5_shc_6_10" = "Experience running business: 6-10 yrs",
                "resp_experience_agg5_shc_11_20" = "Experience running business: 11-20 yrs",
                "resp_experience_agg5_shc_20" = "Experience running business: > 20 yrs",
                "resp_experience_c_5yi" = "Experience running business: Continuous (+5yrs)*",
                "resp_age_c_5yi" = "Age: Continuous (+5yrs)*",
                "resp_age_agg3_shc_35" = "Age: [< 35 yrs]",                
                "resp_age_agg3_shc_55" = "Age:[> 55 yrs]",                 
                "resp_age_agg3_shc_3555" = "Age: [35-55 yrs)",   
                "resp_age_agg6_shc_25" = "Age: [< 25 yrs]",
                "resp_age_agg6_shc_2535" = "Age: [25-35 yrs)",
                "resp_age_agg6_shc_3545" = "Age: [35-45 yrs)",
                "resp_age_agg6_shc_4555" = "Age: [45-55 yrs)",
                "resp_age_agg6_shc_5565" = "Age: [55-65 yrs)",
                "resp_age_agg6_shc_65" = "Age: [65+ yrs]",
                "resp_motivation_oth" = "Motivation to start business: Inherited business or other reason",
                "resp_motivation_lackopp" = "Motivation to start business: Lack of other income opportunities or desire to generate additional income",
                "resp_motivation_entrep" = "Motivation to start business: Desire to have own business",
                "resp_maingoal_grow"  = "Main goal in next 12 months: Grow the business",
                "resp_maingoal_stab"  = "Main goal in next 12 months: Cover business costs",
                "resp_maingoal_leave" = "Main goal in next 12 months: Leave business to get a regular wage paying job or other",
                "resp_riskapproach_aggr" = "Risk tolerance: Aggresively pursue risky opportunities that could generate significant additional income",
                "resp_riskapproach_calc" = "Risk tolerance: Cautiously pursue risk opportunities that could generate a little income",
                "resp_riskapproach_avoid" = "Risk tolerance: Avoid risks even if they could generate additional income",
                "resp_psych_segment_shc_grow" = "Pyschographic orientation: Growth",
                "resp_psych_segment_shc_stab" = "Pyschographic orientation: Stability",
                "resp_psych_segment_shc_surv" = "Pyschographic orientation: Survival",
                "business_size_agg2_shc_1" = "Size: 1 person",
                "business_size_agg2_shc_2_10" = "Size: 2-10 people",
                "business_sector_agg2_shc_mfc" = "Sector: Manufacturing",
                "business_sector_agg2_shc_srv" = "Sector: Services",
                "business_premise_shc_1" = "Premises: Household",
                "business_premise_shc_2" = "Premises: Permanent" ,
                "business_premise_shc_3" = "Premises: Semi-permanent",
                "business_premise_shc_4" = "Premises: Other",
                "business_registered" = "Registration: Business is registered with tax collection bureau",
                
                "resp_pcthhincfrmbus_high" = "Business-household co-dependence: Business contributes over 50% of owner's household income",
                "business_finances_notseparate" = "Business-household co-dependence: Business either does not have a formal financial account or is not separate from owner's account",
                "business_hh_noboundaries" = "Business-household co-dependence: Business operations and finances are not separate from household",
                "business_hh_codep_index" = "Business-household co-dependence: Index",
                
                "tech_has_internet" = "Internet connectivity: Has",
                "tech_has_device" = "Mobile phone/computer/tablet: Uses",
                "tech_has_both" = "Digital technology adoption: Has internet and uses device",
                "tech_has_none" = "Digital technology adoption: Does not have internet and does not use device",
                "tech_cat_none" = "Digital technology adoption: No digital technology used",
                "tech_cat_any1" = "Digital technology adoption: Any 1 use case",
                "tech_cat_any2" = "Digital technology adoption: Any 2 use cases",
                "tech_cat_any3" = "Digital technology adoption: Any 3 use cases",
                "tech_cat_all4" = "Digital technology adoption: All 4 use cases",
                "tech_uses_messaging" = "Messaging apps: Uses",
                "tech_uses_socialmedia" = "Social media: Uses",
                "tech_uses_website" = "Website: Has",
                "tech_uses_ecommerce" = "E-commerce platforms: Uses",
                "tech_uses_software" = "Software for operations: Uses",
                "tech_uses_ai" = "Artificial intelligence: Ever used",
                "tech_uses_digpayments" = "Merchant digital payments: Used in past 12 mos",
                "tech_uses_digloans" = "Digital loans: Used in past 12 mos",
                "tech_uses_diginsurance" = "Digital insurance: Uses",
                "tech_uses_messaging_30da" = "Messaging apps: 30-day active",
                "tech_uses_socialmedia_30da" = "Social media: 30-day active",
                "tech_uses_ecommerce_30da" = "E-commerce platforms: 30-day active",
                "tech_uses_messaging_7da" = "Messaging apps: 7-day active",
                "tech_uses_socialmedia_7da" = "Social media: 7-day active",
                "tech_uses_ecommerce_7da" = "E-commerce platforms: 7-day active",
                "tech_uses_website_imp" = "Website is very or somewhat important to business",
                "tech_uses_software_30da" = "Software for operations (30-day active)",
                "tech_uses_software_7da" = "Software for operations (7-day active)",
                "tech_uses_messaging_shc_dow" = "Messaging apps: Daily or weekly",      
                "tech_uses_messaging_shc_mol" = "Messaging apps: Monthly or less",        
                "tech_uses_messaging_shc_nam" = "Messaging apps: Stopped using",         
                "tech_uses_messaging_shc_nvr" = "Messaging apps: Never used",         
                "tech_uses_socialmedia_shc_dow" = "Social media: Daily or weekly",        
                "tech_uses_socialmedia_shc_mol" = "Social media: Monthly or less",     
                "tech_uses_socialmedia_shc_nam" = "Social media: Stopped using",      
                "tech_uses_socialmedia_shc_nvr" = "Social media: Never used",      
                "tech_uses_ecommerce_shc_dow" = "E-commerce platforms: Daily or weekly",       
                "tech_uses_ecommerce_shc_mol" = "E-commerce platforms: Monthly or less",         
                "tech_uses_ecommerce_shc_nam" = "E-commerce platforms: Stopped using",         
                "tech_uses_ecommerce_shc_nvr" = "E-commerce platforms: Never used",         
                "tech_uses_software_shc_dow" = "Software for operations: Daily or weekly",           
                "tech_uses_software_shc_mol" = "Software for operations: Monthly or less",  
                "tech_uses_software_shc_nam" = "Software for operations: Stopped using",
                "tech_uses_software_shc_nvr" = "Software for operations: Never used", 
                "tech_uses_adoption_score" = "Digital technology adoption score: [0 min -10 max]",
                "tech_function_comms" = "Communicating with customers: Uses",
                "tech_function_mkts" = "Accessing markets: Uses",
                "tech_function_ops" = "Enterprise operations: Uses",
                "tech_function_epay" = "Digital payment acceptance: Uses",
                "tech_function_efin" = "Enterprise digital finance: Uses",
                "tech_function_comms_30da" = "Communicating with customers: 30-day active",
                "tech_function_mkts_30da" = "Accessing markets: 30-day active",
                "tech_function_ops_30da" = "Enterprise operations: 30-day active",
                "tech_function_comms_7da" = "Communicating with customers: 7-day active",
                "tech_function_mkts_7da" = "Accessing markets: 7-day active",
                "tech_function_ops_7da" = "Enterprise operations: 7-day active",
                "tech_adopfactors_demand" = "Adoption factors: Demand from customers/suppliers",            
                "tech_adopfactors_support" = "Adoption factors: Obtaining support to use tech",            
                "tech_adopfactors_comp" = "Adoption factors: Competitive pressure",                
                "tech_adopfactors_other" = "Adoption factors: Other",               
                "tech_adopbenefits_rev" = "Adoption benefits: Increased revenue",                
                "tech_adopbenefits_costs" = "Adoption benefits: Reduced costs",             
                "tech_adopbenefits_customer" = "Adoption benefits: Access to more customers/providers",           
                "tech_adopbenefits_sales" = "Adoption benefits: Faster sales cycle/time-savings",              
                "tech_adopbenefits_cashflow" = "Adoption benefits: Better cash flow management",           
                "tech_adopbenefits_finserv" = "Adoption benefits: Improved access to financial services",          
                "tech_adopbenefits_other" = "Adoption benefits: Other",              
                "tech_adopchllng_diff" = "Adoption challenges: Difficulty using technology",                 
                "tech_adopchllng_cost"= "Adoption challenges: High cost of implementation or maintenance",               
                "tech_adopchllng_trust" = "Adoption challenges: Lack of trust/ security or privacy concerns",               
                "tech_adopchllng_notrlv" = "Adoption challenges: Available tools are not relevant",               
                "tech_adopchllng_infra" = "Adoption challenges: Lack of phones, computers or internet",                
                "tech_adopchllng_other" = "Adoption challenges: Other", 
                
                "perf_rev_reports" = "Businesss performence: Reported monthly revenue (%)", 
                "perf_rev" = "Business performance: Revenues (past month) [LCU]",
                "perf_rev_usd" = "Business performance: Revenues (past month) [USD]",
                "perf_revphrpemp" = "Business performance: Hourly sales per employee [LCU]",
                "perf_revphrpemp_usd" = "Business performance: Hourly sales per employee [USD]", 
                
                 "fin_account_formal" = "Account ownership: Business use a formal account with a financial institution to manage its finances and payment",             
                 "fin_owner_save" = "Business savings: Business owner able to save money regularly out of business income",             
                 "fin_bus_savings_cbnk"= "Business savings account: Commercial bank",         
                 "fin_bus_savings_mfi" = "Business savings account: Microfinance institution",
                 "fin_bus_savings_fintech" = "Business savings account: Fintech",         
                 "fin_bus_savings_sacco" = "Business savings account: Saving and Credit Cooperative",            
                 "fin_bus_savings_group" = "Business savings account: VSLA, ROSCA or Savings group",
                 "fin_bus_savings_mm" = "Business savings account: Mobile money wallet, or e-money",  
                 "fin_bus_savings_other" = "Business savings account: Other",             
                 "fin_bus_savings_channel_inprsn" = "Business savings account, transaction channels: OTC at branch",    
                 "fin_bus_savings_channel_digonly" = "Business savings account, transaction channels: Digital",    
                 "fin_bus_savings_channel_both" = "Business savings account, transaction channels: Both OTC and digital",       
                 "fin_bus_savings_channel_other" = "Business savings account, transaction channels: Other",      
                 "fin_merchpay_cashcheques" = "Merchant payment methods: Cash or cheques",          
                 "fin_merchpay_poscard" = "Merchant payment methods: POS card payments",               
                "fin_merchpay_bnktrnsf" = "Merchant payment methods: Direct bank transfers",              
                "fin_merchpay_online" = "Merchant payment methods: Online payments",                
                "fin_merchpay_mobmoney" = "Merchant payment methods: Mobile money",             
                 "fin_merchpay_instant" = "Merchant payment methods: Instant money transfers",               
                "fin_merchpay_qr" = "Merchant payment methods: QR payments",                    
                "fin_owner_creditcard" = "Credit card: Owner has used card for business purposes",               
                "fin_activeloan_cbnk" = "Active loans in past year: Commercial bank",               
                 "fin_activeloan_mfi" = "Active loans in past year: Microfinance institution",                 
                "fin_activeloan_fintech" = "Active loans in past year: Fintech",             
                "fin_activeloan_sacco" = "Active loans in past year: Saving and Credit Cooperative",            
                "fin_activeloan_group" = "Active loans in past year: VSLA, ROSCA or Savings group",              
                 "fin_activeloan_mm" = "Active loans in past year: Mobile money provider",                  
                "fin_activeloan_platform" = "Active loans in past year: E-commerce platform",            
                "fin_activeloan_supplier" = "Active loans in past year: Supplier",            
                "fin_activeloan_moneylndr" = "Active loans in past year: Moneylender",          
                 "fin_activeloan_ff" = "Active loans in past year: Friends or family",                  
                "fin_activeloan_other" = "Active loans in past year: Other",               
                "fin_activeloan_any" = "Demand for credit: Used a loan from any source in past 12 months",                 
                "fin_activeloan_da_cbnk" = "Applied for loan digitally: Commercial bank",            
                 "fin_activeloan_da_mfi" = "Applied for loan digitally: Microfinance institution",              
                "fin_activeloan_da_fintech" = "Applied for loan digitally: Fintech",          
                "fin_activeloan_da_sacco" = "Applied for loan digitally: Saving and Credit Cooperative",            
                "fin_activeloan_da_group" = "Applied for loan digitally: VSLA, ROSCA or Savings group",           
                 "fin_activeloan_da_mm" =  "Applied for loan digitally: Mobile money provider",               
                "fin_deniedloan" = "Demand for credit: Wanted a loan but could not get one in past 12 months",                     
                "fin_deniedloan_reason_nosuit" = "Reason could not get loan: I did not find a suitable loan",       
                "fin_deniedloan_reason_req" = "Reason could not get loan: I could not fulfill the requirements",         
                 "fin_deniedloan_reason_cost" = "Reason could not get loan: Interest rates or fees were too high",         
                "fin_deniedloan_reason_terms" = "Reason could not get loan: Terms and conditions were difficult to understand",        
                "fin_deniedloan_reason_denied" = "Reason could not get loan: I expected to be denied or applied and was rejected",       
                "fin_deniedloan_reason_other" = "Reason could not get loan: Other",       
                 "fin_activeloan_use_inv" = "Reason could not get loan: Purchase inventory or supplies",             
                "fin_activeloan_use_exp" = "Reason could not get loan: Cover business expenses (e.g. wages, utilities)",             
                "fin_activeloan_use_debt" = "Reason could not get loan: Repay previous debts",            
                "fin_activeloan_use_other" = "Reason could not get loan: Invest in expanding business or workforce",          
                 "fin_demandloan" = "Demand for credit: Used a loan or tried to obtain one in past 12 months",                     
                 "fin_suppliercredit" = "Supplier credit: In past 12 months business has received goods from supplier but paid at a later time",                 
                "fin_channels_trust_physical" = "Most trusted financial services transaction channel: Physical",        
                "fin_channels_trust_digital" = "Most trusted financial services transaction channel: Digital",        
                 "fin_channels_trust_indiff" = "Most trusted financial services transaction channel: Indifferent",          
                "fin_digital_benefits_cus" = "Benefits of digital financial services: Increased number of customers",           
                "fin_digital_benefits_rev" = "Benefits of digital financial services: Increased revenue",           
                "fin_digital_benefits_cst" = "Benefits of digital financial services: Reduced costs",          
                 "fin_digital_benefits_tim" = "Benefits of digital financial services: Saved time",           
                "fin_digital_benefits_cf" = "Benefits of digital financial services: Improve ability to manage cash flow",            
                "fin_digital_benefits_bnk" = "Benefits of digital financial services: Easier access to banking at any time",           
                "fin_digital_benefits_crd" = "Benefits of digital financial services: Improved access to credit",          
                 "fin_digital_benefits_dat" = "Benefits of digital financial services: Access to better data & decision-making",           
                "fin_digital_benefits_none" = "Benefits of digital financial services: No effects",
                
                "fin_openbanking_use" = "Open banking: Has used open banking to securely share financial information between providers", 
                
                "cp_loanrepaydiff" = "Loan repayment difficulty: Business has been unable to pay a full loan installment on-time for any funds that it borrowed",
                "cp_loanrepaydiff_cope_notpay" = "Loan repayment difficulty: I did not repay",      
                "cp_loanrepaydiff_cope_restr" = "Loan repayment difficulty: Restructured the loan",        
                "cp_loanrepaydiff_cope_borr" = "Loan repayment difficulty: Borrowed from another source to repay",         
                "cp_loanrepaydiff_cope_work" = "Loan repayment difficulty: Worked additional hours or took another job",        
                "cp_loanrepaydiff_cope_sellasst" = "Loan repayment difficulty: Sold or pawned a business asset",     
                "cp_loanrepaydiff_cope_usedhh" = "Loan repayment difficulty: Used household money",       
                "cp_loanrepaydiff_cope_other" = "Loan repayment difficulty: Other",       
                "cp_issues_fraud" = "Negative experiences with financial services: Fraud or scams",                    
                "cp_issues_salesp" = "Negative experiences with financial services: Sales pressure from provider",                   
                "cp_issues_badtreat" = "Negative experiences with financial services: Poor treatment by provider",                
                "cp_issues_unxfees" = "Negative experiences with financial services: Paid unexpected fees or penalties",                  
                "cp_issues_crb" = "Negative experiences with financial services: Incorrectly reported to a credit reference bureau",                      
                "cp_issues_trms" = "Negative experiences with financial services: Did not understand how a financial product worked",                    
                "cp_issues_other" = "Negative experiences with financial services: Other",                    
                "cp_issues_any" = "Negative experiences with financial services: Any",                      
                "cp_complaint" = "Negative experiences with financial services: Raised a complaint",                      
                "cp_complaint_no_diff" = "No recourse taken, reason: Too difficult",              
                "cp_complaint_no_knowhow" = "No recourse taken, reason: Did not know how or where to go",            
                "cp_complaint_no_channel" = "No recourse taken, reason: No channel to make an official complaint",           
                "cp_complaint_no_faith" = "No recourse taken, reason: Did not think it would be resolved",             
                "cp_complaint_resolved_yes" = "Negative experiences with financial services: Issue was resolved",          
                "cp_dfs_stopped" = "Negative experiences with financial services: Stopped using digital financial services due to fear of, or experiencing consumer protection risks",  
                
                "risk_largestimpact_shc_corr" = "Main risk in past 36 months: Bribes or corruption", 
                "risk_largestimpact_shc_cost" = "Main risk in past 36 months: Rising costs of inputs or labor", 
                "risk_largestimpact_shc_crme" = "Main risk in past 36 months: Crime (theft, vandalism, etc)", 
                "risk_largestimpact_shc_frau" = "Main risk in past 36 months: Online frauds or scams, cybersecurity", 
                "risk_largestimpact_shc_hlth" = "Main risk in past 36 months: Injuries, illness or any health issues", 
                "risk_largestimpact_shc_none" = "Main risk in past 36 months: No risks faced", 
                "risk_largestimpact_shc_othr" = "Main risk in past 36 months: Other", 
                "risk_largestimpact_shc_wthr" = "Main risk in past 36 months: Extreme weather events", 
                "risk_weather_type_heat"= "Climate risk: Extreme heat", 
                "risk_weather_type_droughts" = "Climate risk: Droughts", 
                "risk_weather_type_floods"  = "Climate risk: Extreme rain, floods or landslides", 
                "risk_weather_type_typhoon"  = "Climate risk: Typhoons or cylcones", 
                "risk_weather_type_floodstyphoon"  = "Climate risk: Extreme rain, floods or landslides*", 
                "risk_weather_type_other"  = "Climate risk: Other", 
                "risk_weather_type_any"  = "Climate risk: Any weather event", 
                "risk_weather_impact_fin"  = "Impact of climate risk on business operations: Decreased sales income and/or profits", 
                "risk_weather_impact_cst"  = "Impact of climate risk on business operations: Increased costs", 
                "risk_weather_impact_ops" = "Impact of climate risk on business operations: Disrupted business operations", 
                "risk_weather_impact_dmg" = "Impact of climate risk on business operations: Business assets damaged, lost or worsened*", 
                "risk_weather_impact_imp" = "Impact of climate risk on business operations: Production or sales improved", 
                "risk_weather_cope_prod" = "Actions to cope with climate risk: Changed what the business sells or produces", 
                "risk_weather_cope_spch" = "Actions to cope with climate risk: Diversified suppliers or sought alternative supply chains", 
                "risk_weather_cope_relo" = "Actions to cope with climate risk: Relocated the business", 
                "risk_weather_cope_cash" = "Actions to cope with climate risk: Used business cash or savings", 
                "risk_weather_cope_loan" = "Actions to cope with climate risk: Borrowed money", 
                "risk_weather_cope_insu" = "Actions to cope with climate risk: Used insurance payouts", 
                "risk_weather_cope_govr" = "Actions to cope with climate risk: Received funds from the government", 
                "risk_weather_cope_hcsh" = "Actions to cope with climate risk: Drew on household cash, savings or other assets", 
                "risk_weather_cope_remi" = "Actions to cope with climate risk: Received money from family or friends", 
                "risk_weather_cope_asst" = "Actions to cope with climate risk: Sold business assets", 
                "risk_weather_cope_noth" = "Actions to cope with climate risk: Did nothing", 
                "risk_weather_cope_othr" = "Actions to cope with climate risk: Other", 
                "risk_weather_cond_ntrc" = "Recovery status from climate risk: Not fully recovered", 
                "risk_weather_cond_rc" = "Recovery status from climate risk: Recovered", 
                "risk_weather_cond_rcbt" = "Recovery status from climate risk: Recovered and in a better position", 
                "risk_weather_adaptspend" = "Climate adaptation: Has invested to reduce impact of future weather risks", 
                
                "resi_efunds_firm_diff_3"  = "Difficulty raising emergency funds: Very difficult", 
                "resi_efunds_firm_diff_2"= "Difficulty raising emergency funds: Somewhat difficult", 
                "resi_efunds_firm_diff_1" = "Difficulty raising emergency funds:  Not difficult at all", 
                "resi_efunds_firm_diff_4" = "Difficulty raising emergency funds: Not possible", 
                
                "resi_efunds_firm_str" = "Difficulty raising emergency funds: Emergency funds group", 
                
                "resi_efunds_firm_source_family" = "Source of emergency funds: Family", 
                "resi_efunds_firm_source_work" = "Source of emergency funds: Work", 
                "resi_efunds_firm_source_firmcsh" = "Source of emergency funds: Business savings", 
                "resi_efunds_firm_source_hhcsh" = "Source of emergency funds: Personal savings", 
                "resi_efunds_firm_source_borrow" = "Source of emergency funds: Borrowing", 
                "resi_efunds_firm_source_sellassets" ="Source of emergency funds: Selling assets",  
                "resi_efunds_firm_source_other" = "Source of emergency funds: Other", 
                
                "resi_efunds_hh_owner_yes" = "Would need to take resources from business to cover household emergency: Yes", 
                "resi_efunds_hh_owner_no" = "Would need to take resources from business to cover household emergency: No", 
                
                "resi_suppchain_cust_diff_1" = "Difficulty of losing supplier or main customer: Not difficult at all", 
                "resi_suppchain_cust_diff_2" = "Difficulty of losing supplier or main customer: Somewhat difficult", 
                "resi_suppchain_cust_diff_3" = "Difficulty of losing supplier or main customer: Very difficult", 
                
                "resi_resp_attitude_chllng_1" = "Response to prior business challenges: Felt overwhelmed and feared closure", 
                "resi_resp_attitude_chllng_2" = "Response to prior business challenges: Viewed challenge as normal part of business", 
                "resi_resp_attitude_chllng_3" = "Response to prior business challenges: Sought new opportunities to expand or pivot",
                 "resi_resp_attitude_chllng_4" = "Response to prior business challenges: I didn't face any significant challenges", 
                
                 "resi_network_conf_3" = "Confidence in social network support: Not confident at all", 
                 "resi_network_conf_2" = "Confidence in social network support: Somewhat confident", 
                 "resi_network_conf_1" = "Confidence in social network support: Very confident", 
                
                "resi_capital_financial" = "Resilience capital: Financial, Can raise emergency funds without major difficulty", 
                "resi_capital_linkages" = "Resilience capital: Structural, Can overcome loss of main customer or supplier without major difficulty", 
                "resi_capital_hh" = "Resilience capital: Financial, Business resources not vulnerable to household shocks", 
                "resi_capital_network" = "Resilience capital: Social, Confident that network can support business if needed", 
                "resi_capital_score_v1" = "Resilience capital: Overall resilience score [0 min -4 max]", 
                "resi_capital_score_v2" = "Resilience capital: Overall resilience score [0 min -3 max]"
                
) 

GROUPS <- c("fullsample" = "All businesses",
            "business_premise" = "Premises type",
            "business_size_agg2" = "Business size",
            "business_sector_agg2" = "Industrial sector",
            "business_sector_agg3" = "Industrial sector",
            "resp_experience_agg5" = "Experience running business (years)",
            "resp_sex_str" = "Gender of business owner or manager",
            "resp_owner_str" = "Respondent type", 
            "business_registration_status" = "Business registered with tax collection bureau?",
            "resp_psych_segment" = "Growth orienation segment",
            "resp_psych_segment_agg2" = "Growth orientation segment", 
            "risk_largestimpact_str" = "Shock with largest impact on business in past 36 months")

GROUP_CAT_LEVELS <- c("All businesses",
                      "Household", "Non-household: Permanent structure", "Non-household: Semi-permanent structure",
                      "Services: trade (re-sale)", "Services: other (eg. transport, construction)", "Manufacturing",
                      "1 person", "2-10 people",
                      "1 yr or less", "2-5 yrs", "6-10 yrs", "11-20 yrs", "> 20 yrs")


