########################################################################

# Global parameters  --------------------------

#####################################################################################

COUNTRIES <- c("Indonesia", "Brazil", "Ethiopia", "Nigeria", "India")
CITIES <- c("Jakarta", "Sao Paulo", "Addis Ababa", "Lagos", "Delhi")
names(CITIES) <- COUNTRIES

WEIGHT_PARAMS <- list(
  "Indonesia" = list("N" = 26293, "n" = 96, "restricted_blocks" = c(23582, 26105, 21436, 16723), "grid_area" = 593),
  "Brazil" = list("N" = NULL, "n" = NULL,  "restricted_blocks" = NULL, "grid_area" = 1015),
  "Ethiopia" = list("N" = 15842, "n" = 98, "restricted_blocks" = c(3585,10239), "grid_area" = 361),
  "Nigeria" = list("N" = 9282, "n" = 99,  "restricted_blocks" = c(2851), "grid_area" = 208),
  "India" = list("N" = 30880, "n" = 98,  "restricted_blocks" = NULL, "grid_area" = 893)
  )

# Exchange rates per USD at 01 June 2024 (LCU per USD) from UN Treasures
# https://treasury.un.org/operationalrates/OperationalRates.php

FX_RATES <- list(
  "Indonesia" = 16262,
  "Brazil" = 5.203,
  "Ethiopia" = 57.042,
  "Nigeria" = 1435.3,
  "India" = 83.31
)

INDICATORS <- c("N_business_total_percluster" = "Total businesses (N)",
                "business_total" = "Total businesses (N)",
                "resp_sex_men" = "Men",
                "resp_sex_women" = "Women",
                "resp_education_agg2_shc_priorless" = "Educational attainment: Primary or less",
                "resp_education_agg2_shc_secormore" = "Educational attainment: Secondary or higher",
                "resp_education_agg4_shc_non" = "Some primary or none",
                "resp_education_agg4_shc_pri" = "Completed primary or some secondary",
                "resp_education_agg4_shc_sec" = "Completed secondary or some university/technical school",
                "resp_education_agg4_shc_trt" = "Completed university/technical school",
                "resp_experience_c" = "Experience running business (yrs)", 
                "resp_experience_agg5_shc_1" = "1 yr or less",
                "resp_experience_agg5_shc_2_5" = "2-5 yrs",
                "resp_experience_agg5_shc_6_10" = "6-10 yrs",
                "resp_experience_agg5_shc_11_20" = "11-20 yrs",
                "resp_experience_agg5_shc_20" = "> 20 yrs",
                "resp_experience_c_5yi" = "Experience running business (+5yrs)*",
                "resp_age_c_5yi" = "Age (+5yrs)*",
                "resp_age_agg3_shc_35" = "[< 35 yrs]",                
                "resp_age_agg3_shc_55" = "[> 55 yrs]",                 
                "resp_age_agg3_shc_3555" = "[35-55 yrs)",   
                "resp_age_agg6_shc_25" = "[< 25 yrs]",
                "resp_age_agg6_shc_2535" = "[25-35 yrs)",
                "resp_age_agg6_shc_3545" = "[35-45 yrs)",
                "resp_age_agg6_shc_4555" = "[45-55 yrs)",
                "resp_age_agg6_shc_5565" = "[55-65 yrs)",
                "resp_age_agg6_shc_65" = "[65+ yrs]",
                "resp_motivation_oth" = "Inherited business or other reason",
                "resp_motivation_lackopp" = "Lack of other income opportunities or desire to generate additional income",
                "resp_motivation_entrep" = "Desire to have own business",
                "resp_maingoal_grow"  = "Grow the business",
                "resp_maingoal_stab"  = "Cover business costs",
                "resp_maingoal_leave" = "Leave business to get a regular wage paying job or other",
                "resp_riskapproach_aggr" = "Aggresively pursue risky opportunities that could generate significant additional income",
                "resp_riskapproach_calc" = "Cautiously pursue risk opportunities that could generate a little income",
                "resp_riskapproach_avoid" = "Avoid risks even if they could generate additional income",
                "resp_psych_segment_shc_grow" = "Growth",
                "resp_psych_segment_shc_stab" = "Stability",
                "resp_psych_segment_shc_surv" = "Survival",
                "business_size_agg2_shc_1" = "Size: 1 person",
                "business_size_agg2_shc_2_10" = "Size: 2-10 people",
                "business_sector_agg2_shc_mfc" = "Sector: Manufacturing",
                "business_sector_agg2_shc_srv" = "Sector: Services",
                "business_premise_shc_1" = "Premises: Household",
                "business_premise_shc_2" = "Premises: Permanent" ,
                "business_premise_shc_3" = "Premises: Semi-permanent",
                "business_premise_shc_4" = "Premises: Other",
                "business_registered" = "Business is registered with tax collection bureau",
                "resp_pcthhincfrmbus_high" = "Business contributes over 50% of owner's household income",
                
                "business_finances_notseparate" = "Business either does not have a formal financial account or is not separate from owner's account",
                "business_hh_noboundaries" = "Business operations and finances are not separate from household",
                "business_hh_codep_index" = "Business-household co-dependence index",
                
                "tech_has_internet" = "Internet connectivity: Has",
                "tech_has_device" = "Mobile phone/computer/tablet: Uses",
                "tech_has_both" = "Has internet and uses device",
                "tech_has_none" = "Does not have internet and does not use device",
                "tech_cat_none" = "No digital technology used",
                "tech_cat_any1" = "Any 1 business function",
                "tech_cat_any2" = "Any 2 business functions",
                "tech_cat_any3" = "Any 3 business functions",
                "tech_cat_all4" = "All 4 business functions",
                "tech_uses_messaging" = "Uses messaging apps",
                "tech_uses_socialmedia" = "Uses social media",
                "tech_uses_website" = "Website: Has",
                "tech_uses_ecommerce" = "E-commerce platforms",
                "tech_uses_software" = "Software for operations",
                "tech_uses_ai" = "Artificial intelligence: Ever used",
                "tech_uses_digpayments" = "Merchant digital payments: Used in past 12 mos",
                "tech_uses_digloans" = "Digital loans: Used in past 12 mos",
                "tech_uses_diginsurance" = "Digital insurance",
                "tech_uses_messaging_30da" = "Messaging apps (30-day active)",
                "tech_uses_socialmedia_30da" = "Social media (30-day active)",
                "tech_uses_ecommerce_30da" = "E-commerce platforms (30-day active)",
                "tech_uses_messaging_7da" = "Messaging apps (7-day active)",
                "tech_uses_socialmedia_7da" = "Social media (7-day active)",
                "tech_uses_ecommerce_7da" = "E-commerce platforms (7-day active)",
                "tech_uses_website_imp" = "Website is very or somewhat important to business",
                "tech_uses_software_30da" = "Software for operations (30-day active)",
                "tech_uses_software_7da" = "Software for operations (7-day active)",
                "tech_uses_messaging_shc_dow" = "Messaging apps: Daily or weekly",      
                "tech_uses_messaging_shc_mol" = "Messaging apps: Monthly or less",        
                "tech_uses_messaging_shc_nam" = "Messaging apps: Stopped using",         
                "tech_uses_messaging_shc_nvr" = "Messaging apps: Never used",         
                "tech_uses_socialmedia_shc_dow" = "Social media: Daily or weekly",        
                "tech_uses_socialmedia_shc_mol" = "Social media: Monthly or less",     
                "tech_uses_socialmedia_shc_nam" = "Social media: Stopped using",      
                "tech_uses_socialmedia_shc_nvr" = "Social media: Never used",      
                "tech_uses_ecommerce_shc_dow" = "E-commerce platforms: Daily or weekly",       
                "tech_uses_ecommerce_shc_mol" = "E-commerce platforms: Monthly or less",         
                "tech_uses_ecommerce_shc_nam" = "E-commerce platforms: Stopped using",         
                "tech_uses_ecommerce_shc_nvr" = "E-commerce platforms: Never used",         
                "tech_uses_software_shc_dow" = "Software for operations: Daily or weekly",           
                "tech_uses_software_shc_mol" = "Software for operations: Monthly or less",  
                "tech_uses_software_shc_nam" = "Software for operations: Stopped using",
                "tech_uses_software_shc_nvr" = "Software for operations: Never used", 
                "tech_uses_adoption_score" = "Digital technology adoption score: [0 min -10 max]",
                "tech_function_comms" = "Communicating with customers",
                "tech_function_mkts" = "Accessing markets",
                "tech_function_ops" = "Enterprise operations",
                "tech_function_epay" = "Merchant payments",
                "tech_function_efin" = "Enterprise digital finance",
                "tech_function_comms_30da" = "Communicating with customers (30-day active)",
                "tech_function_mkts_30da" = "Accessing markets (30-day active)",
                "tech_function_ops_30da" = "Enterprise operations (30-day active)",
                "tech_function_comms_7da" = "Communicating with customers (7-day active)",
                "tech_function_mkts_7da" = "Accessing markets (7-day active)",
                "tech_function_ops_7da" = "Enterprise operations (7-day active)",
                "tech_adopfactors_demand" = "Adoption factors: Demand from customers/suppliers",            
                "tech_adopfactors_support" = "Adoption factors: Obtaining support to use tech",            
                "tech_adopfactors_comp" = "Adoption factors: Competitive pressure",                
                "tech_adopfactors_other" = "Adoption factors: Other",               
                "tech_adopbenefits_rev" = "Adoption benefits: Increased revenue",                
                "tech_adopbenefits_costs" = "Adoption benefits: Reduced costs",             
                "tech_adopbenefits_customer" = "Adoption benefits: Access to more customers/providers",           
                "tech_adopbenefits_sales" = "Adoption benefits: Faster sales cycle/time-savings",              
                "tech_adopbenefits_cashflow" = "Adoption benefits: Better cash flow management",           
                "tech_adopbenefits_finserv" = "Adoption benefits: Improved access to financial services",          
                "tech_adopbenefits_other" = "Adoption benefits: Other",              
                "tech_adopchllng_diff" = "Adoption challenges: Difficulty using technology",                 
                "tech_adopchllng_cost"= "Adoption challenges: High cost of implementation or maintenance",               
                "tech_adopchllng_trust" = "Adoption challenges: Lack of trust/ security or privacy concerns",               
                "tech_adopchllng_notrlv" = "Adoption challenges: Available tools are not relevant",               
                "tech_adopchllng_infra" = "Adoption challenges: Lack of phones, computers or internet",                
                "tech_adopchllng_other" = "Adoption challenges: Other", 
                
                "perf_rev" = "Revenues (past month) [LCU]",
                "perf_rev_usd" = "Revenues (past month) [USD]",
                "perf_revphrpemp" = "Hourly sales per employee [LCU]",
                "perf_revphrpemp_usd" = "Hourly sales per employee [USD]", 
                
                "risk_largestimpact_shc_corr" = "Bribes or corruption", 
                "risk_largestimpact_shc_cost" = "Rising costs of inputs or labor", 
                "risk_largestimpact_shc_crme" = "Crime (theft, vandalism, etc)", 
                "risk_largestimpact_shc_frau" = "Online frauds or scames, cybersecurity", 
                "risk_largestimpact_shc_hlth" = "Injuries, illness or any health issues", 
                "risk_largestimpact_shc_none" = "No risks faced", 
                "risk_largestimpact_shc_othr" = "Other", 
                "risk_largestimpact_shc_wthr" = "Extreme weather events", 
                "risk_weather_type_heat"= "Extreme heat", 
                "risk_weather_type_droughts" = "Droughts", 
                "risk_weather_type_floods"  = "Extreme rain, floods or landslides", 
                "risk_weather_type_typhoon"  = "Typhoons or cylcones", 
                "risk_weather_type_floodstyphoon"  = "Extreme rain, floods or landslides*", 
                "risk_weather_type_other"  = "Other", 
                "risk_weather_type_any"  = "Any weather event", 
                "risk_weather_impact_fin"  = "Decreased sales income and/or profits", 
                "risk_weather_impact_cst"  = "Increased costs", 
                "risk_weather_impact_ops" = "Disrupted business operations", 
                "risk_weather_impact_dmg" = "Business assets damaged, lost or worsened*", 
                "risk_weather_impact_imp" = "Production or sales improved", 
                "risk_weather_cope_prod" = "Changed what the business sells or produces", 
                "risk_weather_cope_spch" = "Diversified suppliers or sought alternative supply chains", 
                "risk_weather_cope_relo" = "Relocated the business", 
                "risk_weather_cope_cash" = "Used business cash or savings", 
                "risk_weather_cope_loan" = "Borrowed money", 
                "risk_weather_cope_insu" = "Used insurance payouts", 
                "risk_weather_cope_govr" = "Received funds from the government", 
                "risk_weather_cope_hcsh" = "Drew on household cash, savings or other assets", 
                "risk_weather_cope_remi" = "Received money from family or friends", 
                "risk_weather_cope_asst" = "Sold business assets", 
                "risk_weather_cope_noth" = "Did nothing", 
                "risk_weather_cope_othr" = "Other", 
                "risk_weather_cond_ntrc" = "Not fully recovered", 
                "risk_weather_cond_rc" = "Recovered", 
                "risk_weather_cond_rcbt" = "Recovered and in a better position", 
                "risk_weather_adaptspend" = "Has invested to reduce impact of future weather risks", 
                
                "resi_efunds_firm_diff_3"  = "Very difficult", 
                "resi_efunds_firm_diff_2"= "Somewhat difficult", 
                "resi_efunds_firm_diff_1" = "Not difficult at all", 
                "resi_efunds_firm_diff_4" = "Not possible", 
                
                "resi_efunds_firm_str" = "Emergency funds group", 
                
                "resi_efunds_firm_source_family" = "Family", 
                "resi_efunds_firm_source_work" = "Work", 
                "resi_efunds_firm_source_firmcsh" = "Business savings", 
                "resi_efunds_firm_source_hhcsh" = "Personal savings", 
                "resi_efunds_firm_source_borrow" = "Borrowing", 
                "resi_efunds_firm_source_sellassets" ="Selling assets",  
                "resi_efunds_firm_source_other" = "Other", 
                
                "resi_efunds_hh_owner_yes" = "Yes", 
                "resi_efunds_hh_owner_no" = "No", 
                
                "resi_suppchain_cust_diff_1" = "Not difficult at all", 
                "resi_suppchain_cust_diff_2" = "Somewhat difficult", 
                "resi_suppchain_cust_diff_3" = "Very difficult", 
                
                "resi_resp_attitude_chllng_1" = "Felt overwhelmed and feared closure", 
                "resi_resp_attitude_chllng_2" = "Viewed challenge as normal part of business", 
                "resi_resp_attitude_chllng_3" = "Sought new opportunities to expand or pivot",
                 "resi_resp_attitude_chllng_4" = "I didn't face any significant challenges", 
                
                 "resi_network_conf_3" = "Not confident at all", 
                 "resi_network_conf_2" = "Somewhat confident", 
                 "resi_network_conf_1" = "Very confident", 
                
                "resi_capital_financial" = "Financial: Can raise emergency funds without major difficulty", 
                "resi_capital_linkages" = "Structural: Can overcome loss of main customer or supplier without major difficulty", 
                "resi_capital_hh" = "Financial: Business resources not vulnerable to household shocks", 
                "resi_capital_network" = "Social: Confident that network can support business if needed", 
                "resi_capital_score_v1" = "Overall resilience score [0 min -4 max]", 
                "resi_capital_score_v2" = "Overall resilience score [0 min -3 max]"
                
) 

GROUPS <- c("fullsample" = "All businesses",
            "business_premise" = "Premises type",
            "business_size_agg2" = "Business size",
            "business_sector_agg2" = "Industrial sector",
            "business_sector_agg3" = "Industrial sector",
            "resp_experience_agg5" = "Experience running business (years)",
            "resp_sex_str" = "Gender of business owner or manager",
            "resp_owner_str" = "Respondent type", 
            "business_registration_status" = "Business registered with tax collection bureau?",
            "resp_psych_segment" = "Growth orienation segment",
            "resp_psych_segment_agg2" = "Growth orientation segment", 
            "risk_largestimpact_str" = "Shock with largest impact on business in past 36 months")

GROUP_CAT_LEVELS <- c("All businesses",
                      "Household", "Non-household: Permanent structure", "Non-household: Semi-permanent structure",
                      "Services: trade (re-sale)", "Services: other (eg. transport, construction)", "Manufacturing",
                      "1 person", "2-10 people",
                      "1 yr or less", "2-5 yrs", "6-10 yrs", "11-20 yrs", "> 20 yrs")


